package com.systex.jbranch.platform.common.util.db;

import java.util.HashMap;
import java.util.Map;

public class DB2Assist implements DBAssist{

	final public static int DUPLICATE_CODE = -803; //db2重覆pk代碼
	
	final private static Map<String, String> RESON_MAPPING = new HashMap<String, String>(); 
	
	static{
		RESON_MAPPING.put("00", "完全的成功完成");
		RESON_MAPPING.put("01", "警告");
		RESON_MAPPING.put("02", "無資料");
		RESON_MAPPING.put("07", "動態 SQL 錯誤");
		RESON_MAPPING.put("08", "連線異常狀況");
		RESON_MAPPING.put("09", "觸發動作異常狀況");
		RESON_MAPPING.put("0A", "不支援的功能");
		RESON_MAPPING.put("0D", "目標類型規格無效");
		RESON_MAPPING.put("0F", "無效的記號");
		RESON_MAPPING.put("OK", "RESIGNAL 陳述式無效");
		RESON_MAPPING.put("0N", "SQL/XML 對映錯誤");
		RESON_MAPPING.put("20", "CASE 陳述式找不到事例");
		RESON_MAPPING.put("21", "基數違規");
		RESON_MAPPING.put("22", "資料異常狀況");
		RESON_MAPPING.put("23", "限制違規");
		RESON_MAPPING.put("24", "無效的游標狀態");
		RESON_MAPPING.put("25", "無效的交易狀態");
		RESON_MAPPING.put("26", "無效的 SQL 陳述式識別字");
		RESON_MAPPING.put("28", "無效的授權規格");
		RESON_MAPPING.put("2D", "無效的交易終止");
		RESON_MAPPING.put("2E", "無效的連線名稱");
		RESON_MAPPING.put("34", "無效的游標名稱");
		RESON_MAPPING.put("36", "游標靈敏度異常狀況");
		RESON_MAPPING.put("38", "外部函數異常狀況");
		RESON_MAPPING.put("39", "外部函數呼叫異常狀況");
		RESON_MAPPING.put("3B", "SAVEPOINT 無效");
		RESON_MAPPING.put("40", "交易 Rollback");
		RESON_MAPPING.put("42", "語法錯誤或存取規則違規");
		RESON_MAPPING.put("44", "WITH CHECK OPTION 違規");
		RESON_MAPPING.put("46", "Java DDL");
		RESON_MAPPING.put("51", "無效的應用程式狀態");
		RESON_MAPPING.put("53", "無效的運算元或不一致的規格");
		RESON_MAPPING.put("54", "超過 SQL 或產品限制");
		RESON_MAPPING.put("55", "物件未在必備 (Prerequisite) 狀態中");
		RESON_MAPPING.put("56", "其他 SQL 或產品錯誤");
		RESON_MAPPING.put("57", "無可用的資源或操作員介入");
		RESON_MAPPING.put("58", "系統錯誤");
		RESON_MAPPING.put("5U", "公用程式");
		RESON_MAPPING.put("00000", "作業執行成功，且未產生任何類型的警告或異常狀況。");
		RESON_MAPPING.put("01002", "發生 DISCONNECT 錯誤。");
		RESON_MAPPING.put("01003", "已從直欄函數的引數將空值消除。");
		RESON_MAPPING.put("01004", "將字串指定給另一個長度較短的字串資料類型時，字串的值遭到截斷。");
		RESON_MAPPING.put("01005", "SQLDA 中的登錄數不夠。");
		RESON_MAPPING.put("01007", "未授與專用權。");
		RESON_MAPPING.put("0100C", "從程序中傳回了一個或多個 ad hoc 結果集。");
		RESON_MAPPING.put("0100D", "在鏈內的下一個結果集上，已重新開啟已關閉的游標。");
		RESON_MAPPING.put("0100E", "程序產生的結果集數目，超過最大容許值。 只有第一個整數結果集傳回給呼叫程式。");
		RESON_MAPPING.put("01503", "結果欄的數目大於所提供的主變數數目。");
		RESON_MAPPING.put("01504", "UPDATE 或 DELETE 陳述式不包括 WHERE 子句。");
		RESON_MAPPING.put("01506", "已對 DATE 或 TIMESTAMP 值作調整，以更正算術運算產生的無效日期。");
		RESON_MAPPING.put("01509", "由於使用者的虛擬機器記憶體不足，已取消游標建立的區塊。");
		RESON_MAPPING.put("01515", "已指定空值給主變數，因為直欄的非空值不在主變數的範圍內。");
		RESON_MAPPING.put("01516", "已忽略不能應用的 WITH GRANT OPTION。");
		RESON_MAPPING.put("01517", "已用替代字元置換無法轉換的字元。");
		RESON_MAPPING.put("01519", "已指定空值給主變數，因為數值超出範圍。");
		RESON_MAPPING.put("01524", "直欄函數的結果不包括因計算算術運算所引起的空值。");
		RESON_MAPPING.put("01526", "隔離層次已提升。");
		RESON_MAPPING.put("01527", "SET 陳述式參照一個 AS 上不存在的特別暫存區。");
		RESON_MAPPING.put("01539", "連線成功，但只應使用 SBCS 字元。");
		RESON_MAPPING.put("01543", "重複限制已被略過。");
		RESON_MAPPING.put("01545", "不合格的欄名被解譯為相關參考。");
		RESON_MAPPING.put("01550", "未建立物件，因為已有具備指定說明的物件存在。");
		RESON_MAPPING.put("01560", "多餘的 GRANT 已被忽略。");
		RESON_MAPPING.put("01562", "資料庫配置檔中的日誌新路徑 (newlogpth) 是無效的。");
		RESON_MAPPING.put("01563", "進入日誌檔的現行路徑 (logpath) 是無效的。 日誌檔路徑已重設為預設值。");
		RESON_MAPPING.put("01564", "已指定空值給主變數，因為除數為零。");
		RESON_MAPPING.put("01565", "在處理回復的查詢之前，已將查詢中發現的值 sNaN 換成值 NaN。");
		RESON_MAPPING.put("01586", "該陳述式導致一或多個表格自動處於「設定完整性擱置」狀態。");
		RESON_MAPPING.put("01589", "陳述式包含多餘的規格。");
		RESON_MAPPING.put("01592", "在參照 SOURCE 功能的 CREATE FUNCTION 陳述式中，可能是：輸入參數的長度、精確度或比例，大於原始功能對應參數的長度、精確度或比例；或 RETURNS 或 CAST FROM 參數的長度、精確度或比例，小於原始功能的長度、 精確度或比例；或CREATE FUNCTION 陳述式中的 CAST FROM 參數，其長度、精確度或比例， 大於 RETURNS 參數的長度、精確度或比例。執行時可能發生截斷（並可能在此時造成錯誤）。");
		RESON_MAPPING.put("01594", "ALL 資訊的 SQLDA 中，項目數不足（亦即，沒有足夠的描述子可傳回明確的名稱）。");
		RESON_MAPPING.put("01595", "該視圖已置換現存的無效視圖。");
		RESON_MAPPING.put("01596", "未替以長字串資料類型為基礎的特殊類型建立比較函數。");
		RESON_MAPPING.put("01598", "嘗試啟動作用中的事件監視器，或停止非作用中的事件監視器。");
		RESON_MAPPING.put("01599", "REBIND 上略過了連結選項。");
		RESON_MAPPING.put("01602", "最佳化層次已被降低。");
		RESON_MAPPING.put("01603", "CHECK DATA 處理程序發現限制違規，並將它們移至異常狀況表格。");
		RESON_MAPPING.put("01604", "已解譯 SQL 陳述式且未執行它。");
		RESON_MAPPING.put("01605", "遞迴共用表格表示式可能包含無限迴圈。");
		RESON_MAPPING.put("01606", "節點或系統資料庫目錄是空的。");
		RESON_MAPPING.put("01607", "唯讀交易中，節點上時間之間的差異超過定義的臨界值。");
		RESON_MAPPING.put("01608", "已置換不受支援的值。");
		RESON_MAPPING.put("01609", "程序產生的結果集數目，超過最大容許值。 只有第一個整數結果集傳回給呼叫程式。");
		RESON_MAPPING.put("01610", "從程序中傳回了一個或多個 ad hoc 結果集。");
		RESON_MAPPING.put("01611", "在鏈內的下一個結果集上，已重新開啟已關閉的游標。");
		RESON_MAPPING.put("01614", "定位器的數目少於結果集的數目。");
		RESON_MAPPING.put("01616", "所估計的 CPU 用量超出資源限制。");
		RESON_MAPPING.put("01618", "需有重新配送節點群組，方可變更資料庫分割。");
		RESON_MAPPING.put("01620", "UNION ALL 的某些基本表格可能是同一個表格。");
		RESON_MAPPING.put("01621", "可能已變更了擷取的 LOB 值。");
		RESON_MAPPING.put("01622", "已順利地完成陳述式，但是在完成陳述式之後，系統發生錯誤。");
		RESON_MAPPING.put("01623", "DEGREE 的值已被忽略。");
		RESON_MAPPING.put("01625", "綱目名稱在 CURRENT PATH 中出現多次。");
		RESON_MAPPING.put("01626", "資料庫僅擁有一個作用中緩衝池。");
		RESON_MAPPING.put("01627", "由於表格正暫停調節中或是不可能有調節狀態，所以 DATALINK 值無效。");
		RESON_MAPPING.put("01632", "並行連線的數目已超出針對產品所定義的。");
		RESON_MAPPING.put("01633", "實體化的查詢表格無法用來最佳化查詢的處理程序。");
		RESON_MAPPING.put("01636", "資料庫管理程式仍未驗證非遞增資料的完整性。");
		RESON_MAPPING.put("01637", "未啟用除錯。");
		RESON_MAPPING.put("01639", "聯合物件可能要求呼叫者要在資料來源物件上有必要的專用權。");
		RESON_MAPPING.put("01641", "Datalink 類型屬性限制結構化類型的使用。");
		RESON_MAPPING.put("01642", "對 USER 最大可能預設值而言，此直欄不夠長。");
		RESON_MAPPING.put("01643", "SQL 常式中對 SQLSTATE 或 SQLCODE 變數的指定可能會被改寫， 而且不會啟動任何 handler。");
		RESON_MAPPING.put("01645", "SQL 程序的可執行檔並未儲存在資料庫型錄中。");
		RESON_MAPPING.put("01648", "因為表格停用了 VALUE COMPRESSION，所以忽略了 COMPRESS 直欄屬性。");
		RESON_MAPPING.put("01649", "已完成緩衝池作業， 但在重新啟動下一個資料庫之前不會生效。");
		RESON_MAPPING.put("01650", "索引與表格統計不一致。");
		RESON_MAPPING.put("01651", "已順利啟動事件監視器，然而可能遺失了部份監視資訊。");
		RESON_MAPPING.put("01652", "因為陳述式環境定義而忽略隔離子句。");
		RESON_MAPPING.put("01653", "授權已授與使用者。因為授權名稱大於 8 個位元組， 所以未考慮到群組。");
		RESON_MAPPING.put("01654", "尚未啟動緩衝池。");
		RESON_MAPPING.put("01655", "已順利建立事件監視器，但是至少有一個事件監視器目標表格已存在。");
		RESON_MAPPING.put("01657", "直到下次啟動資料庫時，緩衝池作業才會生效。");
		RESON_MAPPING.put("01665", "已截斷直欄名稱或標籤。");
		RESON_MAPPING.put("01667", "視圖不能用來最佳化查詢的處理程序。");
		RESON_MAPPING.put("01669", "因為遠端及本端型錄之間的綱目不一致，所以並未完全更新所指定暱稱的統計值。");
		RESON_MAPPING.put("01670", "新表格沒有預設的主要表格空間。");
		RESON_MAPPING.put("01671", "快取陳述式所在的環境與現行環境不同。將採用現行環境來重新最佳化指定的陳述式。");
		RESON_MAPPING.put("01674", "對於查詢效能而言，表格空間屬性並非最佳。");
		RESON_MAPPING.put("01675", "指定的表格空間超出需要。會忽略額外的表格空間。");
		RESON_MAPPING.put("01676", "由於授權 ID 已是資料庫物件的擁有者，因此已忽略傳送作業。");
		RESON_MAPPING.put("01677", "已定義外掛程式之伺服器，會忽略其 wrapper 選項。");
		RESON_MAPPING.put("01678", "對使用者對映的變更僅適用於聯合型錄表格，但不適用於外部使用者對映儲存庫。");
		RESON_MAPPING.put("01679", "無法建立指定授權 ID 的可靠連線。");
		RESON_MAPPING.put("01682", "已從陳述式指定的部份（非全部）的授權 ID 中移除使用信任環境定義的功能。");
		RESON_MAPPING.put("01684", "不支援指定的語言環境。訊息以英文語言環境傳回。");
		RESON_MAPPING.put("01686", "表格空間從 REGULAR 轉換為 LARGE。必須重組或重建此表格空間中的表格索引，以支援大型 RID。");
		RESON_MAPPING.put("01689", "SQL 編譯在未連接至資料來源時即已完成。");
		RESON_MAPPING.put("0168A", "在資料來源上找不到來源程序的資料包主體，或此資料包主體無效。");
		RESON_MAPPING.put("0168C", "小數浮點運算已產生不準確的結果。");
		RESON_MAPPING.put("0168D", "小數浮點運算無效。");
		RESON_MAPPING.put("0168E", "小數浮點運算已產生溢位或下溢。");
		RESON_MAPPING.put("0168F", "小數浮點運算已產生除數為零的運算。");
		RESON_MAPPING.put("0168H", "產品在評估模式下執行。未安裝有效的授權碼。");
		RESON_MAPPING.put("0168M", "變更資料庫配置參數 DECFLT_ROUNDING 可能會有意料之外的結果。");
		RESON_MAPPING.put("0168O", "聯合伺服器收到來自資料來源的不明警告。");
		RESON_MAPPING.put("0168Q", "以下所示為 wrapper 支援的現行資料來源伺服器版本。使用較新版本的 wrapper 可能會導致錯誤或非預期的結果。");
		RESON_MAPPING.put("0168S", "作業已移除。");
		RESON_MAPPING.put("0168T", "已指定 WITH ROW CHANGE COLUMNS ALWAYS DISTINCT，可是資料庫管理程式無法傳回特殊橫列變更直欄。");
		RESON_MAPPING.put("01H51", "MQSeries Application Messaging Interface 的訊息被截斷。");
		RESON_MAPPING.put("01H52", "常式執行已完成，但執行期間發現至少一個錯誤或警告。尚有可用的資訊。");
		RESON_MAPPING.put("01H53", "常式發現警告。請參閱 SQLCODE，以取得詳細資訊。");
		RESON_MAPPING.put("01H54", "程序已成功傳回，但發現到格式或參數內容有錯誤。參數值中錯誤的相關資訊已傳回至輸出參數中。");
		RESON_MAPPING.put("01H55", "程序已成功傳回，但發現到內部處理錯誤。內部錯誤狀況的相關資訊已傳回至輸出參數中。");
		RESON_MAPPING.put("01H56", "程序已成功傳回，但僅支援所指定參數的較高版本。");
		RESON_MAPPING.put("01H57", "程序傳回的輸出不是在所指定的語言環境中。");
		RESON_MAPPING.put("01HN1", "您已將優先順序設定指派給優先順序高於預設系統服務類別 SYSDEFAULTSYSTEMCLASS 的服務類別，且這可能對效能有負面影響。");
		RESON_MAPPING.put("1HXX", "使用者定義的函數或外部程序 CALL 所傳回的有效警告 SQLSTAE。");
		RESON_MAPPING.put("02000", "發生下列異常狀況之一：SELECT INTO 陳述式的結果或 INSERT 陳述式的次選擇為空表格。所搜尋的 UPDATE 或 DELETE 陳述式中識別的橫列數為零。FETCH 陳述式中參照的游標位置，位於結果表格的最後一列之後。");
		RESON_MAPPING.put("02501", "游標位置對目前橫列的 FETCH 來說是無效的。");
		RESON_MAPPING.put("02502", "偵測到刪除或更新孔。");
		RESON_MAPPING.put("02506", "如 RETURN DATA UNTIL 子句所指定，容許發現的錯誤。");
		RESON_MAPPING.put("07001", "主變數的數目對參數記號數目而言不正確。");
		RESON_MAPPING.put("07002", "呼叫參數清單或控制區塊無效。");
		RESON_MAPPING.put("07003", "EXECUTE 陳述式中識別的陳述是選擇陳述，或是不在準備狀態中。");
		RESON_MAPPING.put("07004", "動態參數需要 USING 子句或 INTO 子句。");
		RESON_MAPPING.put("07005", "游標的陳述式名稱識別一備妥的陳述式，此陳述式不能與游標關聯。");
		RESON_MAPPING.put("07006", "輸入主變數由於其資料類型，所以不能使用。");
		RESON_MAPPING.put("08001", "應用程式要求程式無法建立連線。");
		RESON_MAPPING.put("08002", "連線已經存在。");
		RESON_MAPPING.put("08003", "連線不存在。");
		RESON_MAPPING.put("08004", "應用程式伺服器拒絕了連線的建立。");
		RESON_MAPPING.put("08007", "不明的交易解析。");
		RESON_MAPPING.put("08502", "用 SYNCPOINT of TWOPHASE 執行的應用程式處理所發出的 CONNECT 陳述式失敗，因為沒有交易管理程式可用。");
		RESON_MAPPING.put("08504", "在處理程序指定的路徑重新命名配置檔時發現錯誤。");
		RESON_MAPPING.put("08505", "起始設定連續可用性環境失敗。");
		RESON_MAPPING.put("08506", "連線失敗，但已重新建立。");
		RESON_MAPPING.put("08507", "無法重新建立伺服器連線，因為版次不符。");
		RESON_MAPPING.put("09000", "觸發的 SQL 陳述式失敗。");
		RESON_MAPPING.put("0A001", "CONNECT 陳述式無效，因為程序不在可連線狀態中。");
		RESON_MAPPING.put("0A502", "未針對此資料庫實例啟用動作或作業。");
		RESON_MAPPING.put("0A503", "因為潛伏的資料不一致，所以無法編譯聯合插入、更新或刪除作業。");
		RESON_MAPPING.put("0D000", "目標結構資料類型規格是來源結構資料類型適當的次類型。");
		RESON_MAPPING.put("0E000", "路徑名稱清單無效。");
		RESON_MAPPING.put("0F001", "LOB 記號變數目前不代表任何值。");
		RESON_MAPPING.put("0K000", "RESIGNAL 陳述式不在處理程式中。");
		RESON_MAPPING.put("0N002", "字元無法對映到有效的 XML 字元。");
		RESON_MAPPING.put("10000", "XQuery 錯誤。");
		RESON_MAPPING.put("10501", "XQuery 表示式漏掉指定靜態或動態環境定義元件。");
		RESON_MAPPING.put("10502", "在 XQuery 表示式前言中發現錯誤。");
		RESON_MAPPING.put("10503", "XQuery 或 XPath 表示式中定義了重複的名稱。");
		RESON_MAPPING.put("10504", "XQuery 名稱空間宣告指定了無效的 URI。");
		RESON_MAPPING.put("10505", "XQuery 表示式中，遺失了字元、記號或子句或其無效。");
		RESON_MAPPING.put("10506", "XQuery 表示式參照未定義的名稱。");
		RESON_MAPPING.put("10507", "處理 XPath 或 XQuery 表示式時發現類型錯誤。");
		RESON_MAPPING.put("10508", "XQuery 表示式包括無效的名稱表示式或內容表示式。");
		RESON_MAPPING.put("10509", "指定了不受支援的 XQuery 語言功能。");
		RESON_MAPPING.put("10510", "字串文字未指定為強制轉型表示式的運算元或建構子函數的引數。");
		RESON_MAPPING.put("10601", "處理 XQuery 函數或運算子時發現運算錯誤。");
		RESON_MAPPING.put("10602", "處理 XQuery 函數或運算子時發現強制轉型錯誤。");
		RESON_MAPPING.put("10603", "處理 XQuery 函數或運算子時發現字元處理錯誤。");
		RESON_MAPPING.put("10604", "未提供用於處理 XQuery 函數的文件環境定義。");
		RESON_MAPPING.put("10605", "處理 XQuery 函數或運算子時發現日期時間錯誤。");
		RESON_MAPPING.put("10606", "沒有用於處理 XQuery 函數或運算子的環境定義項目。");
		RESON_MAPPING.put("10607", "處理 XQuery 函數或運算子時發現名稱空間錯誤。");
		RESON_MAPPING.put("10608", "在 XQuery 函數或運算子的引數中發現錯誤。");
		RESON_MAPPING.put("10609", "處理 XQuery 函數或運算子時發現正規表示式錯誤。");
		RESON_MAPPING.put("10610", "處理 XQuery 函數或運算子時發現類型錯誤。");
		RESON_MAPPING.put("10611", "處理 XQuery 函數或運算子時發現無法識別的錯誤。");
		RESON_MAPPING.put("10701", "已在轉換表示式的修改子句外使用 XQuery 更新表示式。");
		RESON_MAPPING.put("10702", "轉換表示式的修改子句中的 XQuery 表示式，是非更新表示式或空白順序表示式。");
		RESON_MAPPING.put("10703", "XQuery 基本更新表示式的目標節點無效。");
		RESON_MAPPING.put("10704", "XQuery 轉換表示式包括不相容的基本更新表示式。");
		RESON_MAPPING.put("10705", "XQuery 轉換表示式在複製子句中包括一個不是單一 XML 節點的已指派值。");
		RESON_MAPPING.put("10706", "XQuery 取代表示式的取代順序含有無效的節點。");
		RESON_MAPPING.put("10707", "XQuery 轉換表示式的結果不是 XQuery 及 XPath 資料模型的有效實例。");
		RESON_MAPPING.put("10708", "XQuery 更新表示式引用新的名稱空間連結，而該連結與另一個更新表示式或某個元素節點的範圍內名稱空間相衝突。");
		RESON_MAPPING.put("10709", "處理指令節點的重新命名指定了一個含有非空白字首的完整名稱。");
		RESON_MAPPING.put("10901", "XQuery 表示式中的 QName 長度超出產品限制。");
		RESON_MAPPING.put("10902", "XQuery 整體值超出 DB2 XQuery 運算子或函數的長度限制。");
		RESON_MAPPING.put("10903", "已超出相符 XQuery 節點數的內部限制。");
		RESON_MAPPING.put("20000", "CASE 陳述式找不到此事例。");
		RESON_MAPPING.put("21000", "SELECT INTO 的結果是包含多列的結果表格， 或者基本述詞的子查詢結果有多個值。");
		RESON_MAPPING.put("21501", "加入自我參照表格中的多列 INSERT 是無效的。");
		RESON_MAPPING.put("21502", "主要索引鍵的多列 UPDATE 是無效的。");
		RESON_MAPPING.put("21504", "在使用 RESTRICT 或 SET NULL 刪除規則的自我參照表格上作多列 DELETE 是無效的。");
		RESON_MAPPING.put("21505", "橫列函數必須傳回不超過一橫列。");
		RESON_MAPPING.put("21506", "表格的同一橫列，僅可為更新、刪除或插入作業中其中一項的目標。");
		RESON_MAPPING.put("21507", "為管理作業所指定的 SQL 陳述式結果導致多個橫列或欄數錯誤。");
		RESON_MAPPING.put("22001", "字元資料，發生右側截斷； 例如，更新或插入值的字串太長而無法放入欄內， 或者日期時間值太小而不能指定給主變數。");
		RESON_MAPPING.put("22002", "偵測到空值或缺少指示器參數； 例如，空值不能指定給主變數，因為沒有指定指示符變數。");
		RESON_MAPPING.put("22003", "數值超出範圍。");
		RESON_MAPPING.put("22004", "定義為 PARAMETER STYLE GENERAL 的程序，或以非空值引數呼叫的類型保留方法不能傳回空值。");
		RESON_MAPPING.put("22007", "偵測到無效的日期時間格式；亦即，指定了無效的字串表示法或值。");
		RESON_MAPPING.put("22008", "發生日期時間欄位溢位；例如，對日期或時間戳記的算術運算結果不在日期的有效範圍內。");
		RESON_MAPPING.put("2200G", "不符合最特定的類型。");
		RESON_MAPPING.put("2200L", "XML 值不是具有單一根元素之形式完整的文件。");
		RESON_MAPPING.put("2200M", "無法將值剖析為形式完整的 XML 文件，或無法根據 XML 綱目對其進行驗證。");
		RESON_MAPPING.put("2200S", "XML 註解無效。");
		RESON_MAPPING.put("2200T", "XML 處理指令無效。");
		RESON_MAPPING.put("2200W", "XML 值包含無法序列化的資料。");
		RESON_MAPPING.put("22011", "子字串發生錯誤；例如，SUBSTR 的引數超出範圍。");
		RESON_MAPPING.put("22012", "用零作除數無效。");
		RESON_MAPPING.put("22018", "CAST、DECIMAL、FLOAT、或 INTEGER 純量函數的字元值無效。");
		RESON_MAPPING.put("22019", "LIKE 述詞有無效的跳出字元。");
		RESON_MAPPING.put("22021", "字元不在編碼字集中。");
		RESON_MAPPING.put("22024", "以 NUL 終止的輸入主變數或參數並未包含 NUL。");
		RESON_MAPPING.put("22025", "LIKE 述詞字串型樣包含一個無效出現的跳出字元。");
		RESON_MAPPING.put("2202D", "空值實例會與轉換方法搭配使用。");
		RESON_MAPPING.put("2202E", "陣列元素錯誤。");
		RESON_MAPPING.put("2202F", "陣列資料，右邊截斷。");
		RESON_MAPPING.put("2202H", "TABLESAMPLE 子句中的範例大小無效。");
		RESON_MAPPING.put("22501", "可變長度字串的長度控制欄位為負值或大於最大值。");
		RESON_MAPPING.put("22504", "混合資料值無效。");
		RESON_MAPPING.put("22506", "因為 TOD 時鐘功能失常或作業系統時區參數超出範圍， 所以參照日期時間特殊登錄無效。");
		RESON_MAPPING.put("22522", "CCSID 值根本無效，對資料類型或次類型無效，或對編碼方法無效。");
		RESON_MAPPING.put("22525", "資料分割鍵值無效。");
		RESON_MAPPING.put("22526", "按鍵轉換函數未產生列或產生複製列。");
		RESON_MAPPING.put("22527", "多重橫列插入中偵測到無效的輸入資料。");
		RESON_MAPPING.put("22531", "內建或系統提供的常式的引數已導致錯誤。");
		RESON_MAPPING.put("22532", "在 XML 綱目儲存庫中找不到 XSROBJECT。");
		RESON_MAPPING.put("22533", "在 XML 綱目儲存庫中找不到唯一的 XSROBJECT。");
		RESON_MAPPING.put("22534", "未使用併入或重新定義，將 XML 綱目文件連接至其他 XML 綱目文件。");
		RESON_MAPPING.put("22535", "XML 綱目不會宣告指定的廣域元素。");
		RESON_MAPPING.put("22536", "XML 值不包含所需的根元素。");
		RESON_MAPPING.put("22538", "XML 綱目更新與現存的 XML 綱目不相容。");
		RESON_MAPPING.put("225D1", "未對分解作業啟用指定的 XML 綱目。");
		RESON_MAPPING.put("225D2", "分解 XML 文件期間 SQL 發生錯誤。");
		RESON_MAPPING.put("225D3", "分解 XML 文件時發現對 XML 綱目類型無效的值。");
		RESON_MAPPING.put("225D4", "分解 XML 文件時發現對目標 SQL 類型無效的值。");
		RESON_MAPPING.put("225D5", "分解 XML 文件時發現在環境定義中不明或無效的 XML 節點。");
		RESON_MAPPING.put("225D6", "指定的 XML 綱目需要移轉至現行版本，以支援分解。");
		RESON_MAPPING.put("225D7", "分解 XML 文件時發現不是 XML 綱目中 complexType 的廣域元素的根元素。");
		RESON_MAPPING.put("225DE", "無法對分解作業啟用 XML 綱目。");
		RESON_MAPPING.put("225X0", "XSLT 處理器已傳回錯誤。");
		RESON_MAPPING.put("23001", "RESTRICT 更新或刪除規則阻止更新或刪除母索引鍵。");
		RESON_MAPPING.put("23502", "插入或更新值為空值，但該欄不能包含空值。");
		RESON_MAPPING.put("23503", "外部索引鍵的插入或變更值無效。");
		RESON_MAPPING.put("23504", "NO ACTION 更新或刪除規則阻止更新或刪除母索引鍵。");
		RESON_MAPPING.put("23505", "由唯一索引或唯一限制強制的限制，有違規發生。");
		RESON_MAPPING.put("23510", "使用 RLST 表格所強加的指令時，發生了違反限制。");
		RESON_MAPPING.put("23511", "無法刪除原始橫列，因為核對限制約束了刪除。");
		RESON_MAPPING.put("23512", "不能新增核對限制，因為表格包含不滿足限制定義的列。");
		RESON_MAPPING.put("23513", "INSERT 或 UPDATE 的結果列，不符核對限制定義。");
		RESON_MAPPING.put("23514", "檢查資料處理程序發現限制違規。");
		RESON_MAPPING.put("23515", "無法建立唯一索引或新增唯一限制，因為表格包含指定索引鍵的重複值。");
		RESON_MAPPING.put("23520", "無法定義外部索引鍵，因為它所有的值都不等於母表格的母索引鍵。");
		RESON_MAPPING.put("23521", "目錄表格的更新違反內部限制。");
		RESON_MAPPING.put("23522", "已用盡識別直欄或順序值的範圍。");
		RESON_MAPPING.put("23523", "對安全標籤直欄提供的值無效。");
		RESON_MAPPING.put("23524", "UNION ALL 視圖內有無效的橫列移動。");
		RESON_MAPPING.put("23525", "無法插入或更新 XML 值，因為在 XML 直欄上插入或更新索引時，偵測到錯誤。");
		RESON_MAPPING.put("23526", "無法在 XML 直欄上建立索引，因為在將 XML 值插入索引時，偵測到錯誤。");
		RESON_MAPPING.put("24501", "所識別的游標未開啟。");
		RESON_MAPPING.put("24502", "OPEN 陳述式中識別的游標已經開啟。");
		RESON_MAPPING.put("24504", "UPDATE、DELETE、SET 或 GET 陳述式中識別的游標未放在一列上。");
		RESON_MAPPING.put("24506", "PREPARE 中識別的陳述式是一開啟游標的陳述式。");
		RESON_MAPPING.put("24510", "嘗試對刪除孔或更新孔執行 UPDATE 或 DELETE 作業。");
		RESON_MAPPING.put("24512", "結果表格與基本表格不相符。");
		RESON_MAPPING.put("24513", "不允許 FETCH NEXT、PRIOR、CURRENT 或 RELATIVE，因為游標的位置未知。");
		RESON_MAPPING.put("24514", "先前的錯誤已停用這個游標。");
		RESON_MAPPING.put("24516", "游標已指定給一個結果集。");
		RESON_MAPPING.put("24517", "外部函數或方法開啟了游標。");
		RESON_MAPPING.put("25000", "在環境定義中指定插入、更新或刪除作業程序呼叫是無效的。");
		RESON_MAPPING.put("25001", "陳述式只能作為工作單元中的第一個陳述式。");
		RESON_MAPPING.put("25501", "陳述式只能作為工作單元中的第一個陳述式。");
		RESON_MAPPING.put("25502", "無法在單一交易中發生多次作業。");
		RESON_MAPPING.put("26501", "所識別的陳述式不存在。");
		RESON_MAPPING.put("27000", "試圖在相同的 SQL 陳述式中多次變更相同表格的相同橫列。");
		RESON_MAPPING.put("28000", "授權名稱無效。");
		RESON_MAPPING.put("2D521", "SQL COMMIT 或 ROLLBACK 在現行作業環境中是無效的。");
		RESON_MAPPING.put("2D522", "在 ATOMIC 複合陳述式中不容許 COMMIT 及 ROLLBACK。");
		RESON_MAPPING.put("2D528", "動態 COMMIT 對於應用程式執行環境是無效的。");
		RESON_MAPPING.put("2D529", "動態 ROLLBACK 對於應用程式執行環境是無效的。");
		RESON_MAPPING.put("2E000", "連線名稱無效。");
		RESON_MAPPING.put("34000", "游標名稱無效。");
		RESON_MAPPING.put("36001", "無法定義所指定 Select 陳述式的 SENSITIVE 游標。");
		RESON_MAPPING.put("38XXX", "外部常式或觸發程式所傳回的有效錯誤 SQLSTATE。");
		RESON_MAPPING.put("38001", "外部常式不能執行 SQL 陳述式。");
		RESON_MAPPING.put("38002", "常式試圖修改資料，但常式未定義成 MODIFIES SQL DATA。");
		RESON_MAPPING.put("38003", "常式中不容許使用此陳述式。");
		RESON_MAPPING.put("38004", "常式試圖讀取資料，但常式未定義成 READS SQL DATA。");
		RESON_MAPPING.put("38501", "當呼叫使用者定義的函數、外部程序或觸發程式（使用 SIMPLE CALL 或 SIMPLE CALL WITH NULLS 呼叫慣例）時，發生了錯誤。");
		RESON_MAPPING.put("38502", "外部函數不能執行 SQL 陳述式。");
		RESON_MAPPING.put("38503", "使用者定義的函數已異常終止。");
		RESON_MAPPING.put("38504", "使用者定義的函數已被使用者岔斷，以停止可能的迴路狀況。");
		RESON_MAPPING.put("38505", "FINAL CALL 的常式中不容許使用 SQL 陳述式。");
		RESON_MAPPING.put("38506", "OLE DB 提供者傳回錯誤，表示函數失敗。");
		RESON_MAPPING.put("38552", "SYSFUN 綱目（由 IBM 供應）中的功能已異常終止。 ");
		RESON_MAPPING.put("38553", "系統綱目中的常式因錯誤而終止。");
		RESON_MAPPING.put("38554", "程序發現不受支援的參數版本號碼。");
		RESON_MAPPING.put("38H01", "MQSeries 函數無法起始設定。");
		RESON_MAPPING.put("38H02", "MQSeries Application Messaging Interface 無法終止階段作業。");
		RESON_MAPPING.put("38H03", "MQSeries Application Messaging Interface 無法適當地處理訊息。");
		RESON_MAPPING.put("38H04", "MQSeries Application Messaging Interface 無法傳送訊息。");
		RESON_MAPPING.put("38H05", "MQSeries Application Messaging Interface 無法讀取/接收訊息。");
		RESON_MAPPING.put("38H06", "MQSeries Application Messaging Interface 的（取消）訂閱需求失敗。");
		RESON_MAPPING.put("38H07", "「MQSeries 應用程式傳訊介面」無法確定工作單元。");
		RESON_MAPPING.put("38H08", "「MQSeries 應用程式傳訊介面」原則錯誤。");
		RESON_MAPPING.put("38H09", "MQSeries XA（兩階段確定）API 呼叫錯誤。");
		RESON_MAPPING.put("38H0A", "「MQSeries 應用程式傳訊介面」無法 rollback 工作單元。");
		RESON_MAPPING.put("38H10", "文字搜尋處理期間發生錯誤。");
		RESON_MAPPING.put("38H11", "無法取得文字搜尋支援。");
		RESON_MAPPING.put("38H12", "直欄上不接受文字搜尋，因為該直欄上沒有文字搜尋索引。");
		RESON_MAPPING.put("38H13", "衝突的搜尋伺服器管理程序或指令正在相同的文字搜尋索引上執行。");
		RESON_MAPPING.put("38H14", "搜尋伺服器管理程序或指令錯誤。");
		RESON_MAPPING.put("39001", "使用者定義的函數傳回無效的 SQLSTATE。");
		RESON_MAPPING.put("39004", "IN 或 INOUT 引數不容許空值。");
		RESON_MAPPING.put("39501", "與引數關聯的醒目位元組已被修改。");
		RESON_MAPPING.put("3B001", "儲存點無效。");
		RESON_MAPPING.put("3B002", "已達到最大儲存點數目。");
		RESON_MAPPING.put("3B501", "偵測到重複的儲存點名稱。");
		RESON_MAPPING.put("3B502", "指定了 RELEASE 或 ROLLBACK TO SAVEPOINT，但是儲存點不存在。");
		RESON_MAPPING.put("3B503", "觸發程式或廣域交易中不容許使用 SAVEPOINT、RELEASE SAVEPOINT 或 ROLLBACK TO SAVEPOINT。");
		RESON_MAPPING.put("40001", "發生具有自動 Rollback 的死鎖或逾時。");
		RESON_MAPPING.put("40003", "陳述式完成情況不明。");
		RESON_MAPPING.put("40504", "系統錯誤造成工作單元 Rollback。");
		RESON_MAPPING.put("40506", "已 RollBack 現行交易，因為發生了一個 SQL 錯誤。");
		RESON_MAPPING.put("40507", "已 RollBack 現行交易，因為建立索引時發生錯誤。");
		RESON_MAPPING.put("42501", "此授權 ID 沒有專用權可在識別的物件上執行指定的作業。");
		RESON_MAPPING.put("42502", "此授權 ID 沒有專用權可執行指定的作業。");
		RESON_MAPPING.put("42504", "無法從指定的授權名稱撤消指定的專用權、安全標籤、豁免或角色。");
		RESON_MAPPING.put("42506", "發生擁有者授權失敗。");
		RESON_MAPPING.put("42508", "不能將指定的資料庫專用權授予 PUBLIC。");
		RESON_MAPPING.put("42509", "因為 DYNAMICRULES 選項，SQL 陳述式未獲授權。");
		RESON_MAPPING.put("42511", "無法擷取 DATALINK 值。");
		RESON_MAPPING.put("42512", "授權 ID 不具有對受保護直欄的存取權。");
		RESON_MAPPING.put("42514", "授權 ID 不具有物件所有權的必要專用權。");
		RESON_MAPPING.put("42516", "使用者對映儲存庫的鑑別失敗。");
		RESON_MAPPING.put("42517", "不接受指定的授權 ID 使用信任環境定義。");
		RESON_MAPPING.put("42519", "這個授權 ID 無法在受保護的表格上執行作業。");
		RESON_MAPPING.put("42520", "因為授權 ID 沒有安全標籤，所以無法執行內建函數。");
		RESON_MAPPING.put("42521", "無法將權限或專用權授與給指定的授權 ID。");
		RESON_MAPPING.put("42522", "此授權 ID 沒有可保護直欄或從直欄中移除保護的認證。");
		RESON_MAPPING.put("42601", "字元、記號或子句無效或缺少。");
		RESON_MAPPING.put("42602", "偵測到名稱中無效的字元。");
		RESON_MAPPING.put("42603", "偵測到未終止的字串常數。");
		RESON_MAPPING.put("42604", "偵測到無效的數字或字串常數。");
		RESON_MAPPING.put("42605", "指定給純量函數的引數數目是無效的。");
		RESON_MAPPING.put("42606", "偵測到無效的十六進位常數。");
		RESON_MAPPING.put("42607", "直欄函數的運算元無效。");
		RESON_MAPPING.put("42608", "在 VALUES 或指派陳述式中使用 NULL 或 DEFAULT 是無效的。");
		RESON_MAPPING.put("42609", "運算子或述詞的所有運算元都是參數記號。");
		RESON_MAPPING.put("42610", "不允許參數記號。");
		RESON_MAPPING.put("42611", "直欄、引數、參數或廣域變數定義無效。");
		RESON_MAPPING.put("42612", "陳述式字串是一種 SQL 陳述式，在其所處的環境定義中，不能接受此 SQL 陳述式。");
		RESON_MAPPING.put("42613", "子句是互斥的。");
		RESON_MAPPING.put("42614", "重複關鍵字是無效的。");
		RESON_MAPPING.put("42615", "偵測到無效的選擇方案。");
		RESON_MAPPING.put("42616", "指定無效的選項。");
		RESON_MAPPING.put("42617", "陳述式字串是空白或空的。");
		RESON_MAPPING.put("42618", "不允許主變數。");
		RESON_MAPPING.put("42620", "已使用 UPDATE 子句指定唯讀 SCROLL。");
		RESON_MAPPING.put("42621", "核對限制無效。");
		RESON_MAPPING.put("42622", "名稱或標籤太長。");
		RESON_MAPPING.put("42623", "無法指定 DEFAULT 子句。");
		RESON_MAPPING.put("42625", "CASE 表示式無效。");
		RESON_MAPPING.put("42627", "必須在使用 EXPRESSION AS 子句的述詞規格之前指定 RETURNS 子句。");
		RESON_MAPPING.put("42628", "轉換定義中的 TO SQL 或 FROM SQL 轉換函數定義超過一個。");
		RESON_MAPPING.put("42629", "SQL 常式必須指定參數名稱。");
		RESON_MAPPING.put("42630", "SQLSTATE 或 SQLCODE 變數宣告不能在巢狀複合陳述式中。");
		RESON_MAPPING.put("42631", "SQL 函數或方法中的 RETURN 陳述式必須包括回覆值。");
		RESON_MAPPING.put("42633", "XMLATTRIBUTES 或 XMLFOREST 的引數需要 AS 子句。");
		RESON_MAPPING.put("42634", "XML 名稱無效。");
		RESON_MAPPING.put("42635", "XML 名稱空間字首無效。");
		RESON_MAPPING.put("42636", "遺失 BY REF 子句或用法有誤。");
		RESON_MAPPING.put("42637", "不能在 DECLARE CURSOR 陳述式中指定 XQuery 表示式。");
		RESON_MAPPING.put("42701", "在插入或更新作業或 SET 轉移變數陳述式中偵測到重複直欄名稱。");
		RESON_MAPPING.put("42702", "由於名稱重複，所以直欄參照不明確。");
		RESON_MAPPING.put("42703", "偵測到未定義的直欄、屬性或參數。");
		RESON_MAPPING.put("42704", "偵測到未定義的物件或限制名稱。");
		RESON_MAPPING.put("42705", "偵測到未定義的伺服器名稱。");
		RESON_MAPPING.put("42707", "ORDER BY 中的直欄名稱並不識別結果表格的直欄。");
		RESON_MAPPING.put("42709", "索引鍵直欄清單中指定重複的直欄名稱。");
		RESON_MAPPING.put("42710", "偵測到重複的物件或限制名稱。");
		RESON_MAPPING.put("42711", "物件定義或 ALTER 陳述式中偵測到重複的直欄名稱或屬性名稱。");
		RESON_MAPPING.put("42712", "FROM 子句中偵測到重複的表格指定碼。");
		RESON_MAPPING.put("42713", "物件清單中偵測到重複物件。");
		RESON_MAPPING.put("42720", "節點目錄中找不到遠端資料庫的節點名稱。");
		RESON_MAPPING.put("42723", "綱目中已存在具有相同標記的函數。");
		RESON_MAPPING.put("42724", "用於使用者定義的函數或程序的外部程式，無法存取。");
		RESON_MAPPING.put("42725", "雖然已直接參照常式（不是用標記或特定實例名稱），但是該常式有多個特定實例。");
		RESON_MAPPING.put("42726", "偵測到指名的來源表格有重複的名稱。");
		RESON_MAPPING.put("42727", "沒有新表格的預設主要表格空間。");
		RESON_MAPPING.put("42728", "節點群組定義中偵測到重複的節點。");
		RESON_MAPPING.put("42729", "該節點未定義。");
		RESON_MAPPING.put("42730", "儲存器名稱已由另一個表格空間使用。");
		RESON_MAPPING.put("42731", "儲存器名稱已由這個表格空間使用。");
		RESON_MAPPING.put("42732", "偵測到 SET CURRENT PATH 陳述式中重複的綱目名稱。");
		RESON_MAPPING.put("42734", "偵測到有重複的參數名稱、SQL 變數名稱、游標名稱、條件名稱或標籤。");
		RESON_MAPPING.put("42735", "並未為緩衝池定義表格空間的節點群組。");
		RESON_MAPPING.put("42736", "找不到 LEAVE 陳述式上指定的標籤或標籤無效。");
		RESON_MAPPING.put("42737", "未定義處理程式所指定的條件。");
		RESON_MAPPING.put("42738", "在 FOR 陳述式的 DECLARE CURSOR 陳述式中，所指定的直欄名稱重複或未命名。");
		RESON_MAPPING.put("42739", "偵測到重複轉換。");
		RESON_MAPPING.put("42740", "指定的類型找不到轉換。 沒有轉換被捨棄。");
		RESON_MAPPING.put("42741", "資料類型沒有定義轉換群組。");
		RESON_MAPPING.put("42742", "類型表格或類型視圖的階層結構中已有相同類型的子表格或子視圖。");
		RESON_MAPPING.put("42743", "索引範圍內找不到搜尋方法。");
		RESON_MAPPING.put("42744", "轉換群組中沒有定義 TO SQL 或 FROM SQL 轉換函數。");
		RESON_MAPPING.put("42745", "常式會定義一個置換現存方法的關係。");
		RESON_MAPPING.put("42746", "在同一個類型階層結構中，方法名稱不能與結構化類型名稱相同。");
		RESON_MAPPING.put("42748", "資料庫的儲存體路徑已經存在，或指定了多次。");
		RESON_MAPPING.put("42749", "具有相同目標名稱空間及綱目位置的 XML 綱目文件，已存在於 XML 綱目。");
		RESON_MAPPING.put("4274A", "在 XML 綱目儲存庫中找不到 XSROBJECT。");
		RESON_MAPPING.put("4274B", "在 XML 綱目儲存庫中找不到唯一的 XSROBJECT。");
		RESON_MAPPING.put("4274C", "在信任環境定義中找不到指定的屬性。");
		RESON_MAPPING.put("4274D", "指定的屬性已經存在於信任環境定義中。");
		RESON_MAPPING.put("4274F", "安全標籤元件中未定義元件元素。");
		RESON_MAPPING.put("4274G", "安全標籤元件未在給定安全標籤的原則中定義。");
		RESON_MAPPING.put("4274H", "指定的安全原則中不存在指定的存取規則。");
		RESON_MAPPING.put("4274I", "指定的安全原則中不存在安全標籤。");
		RESON_MAPPING.put("4274J", "這個緩衝池已使用資料庫分割區群組。");
		RESON_MAPPING.put("42802", "插入或更新值的數目與直欄數不同。");
		RESON_MAPPING.put("42803", "SELECT 或 HAVING 子句中的直欄參照無效， 因為它不是群組直欄；或者 GROUP BY 子句中的直欄參照無效。");
		RESON_MAPPING.put("42804", "CASE 表示式中的結果表示式不相容。");
		RESON_MAPPING.put("42805", "ORDER BY 子句中的整數並不識別結果表格的直欄。");
		RESON_MAPPING.put("42806", "不能指定值給主變數，因為資料類型不相容。");
		RESON_MAPPING.put("42807", "此物件上不允許 INSERT、UPDATE 或 DELETE。");
		RESON_MAPPING.put("42808", "插入或更新作業中識別的直欄不可更新。");
		RESON_MAPPING.put("42809", "所識別的物件不是適用該陳述式的物件類型。");
		RESON_MAPPING.put("42810", "FOREIGN KEY 子句無法辨識基本表格。");
		RESON_MAPPING.put("42811", "指定的直欄數與 SELECT 子句中的直欄數不同。");
		RESON_MAPPING.put("42813", "WITH CHECK OPTION 不能用於指定的視圖。");
		RESON_MAPPING.put("42814", "無法捨棄直欄，因為它是表格中唯一的直欄。");
		RESON_MAPPING.put("42815", "資料類型、長度、比例、值或 CCSID 無效。");
		RESON_MAPPING.put("42816", "表示式中的日期時間值或期間無效。");
		RESON_MAPPING.put("42817", "因為視圖或限制與直欄相依，並指定了 RESTRICT，或是直欄隸屬於分割鍵，或是安全標籤直欄，所以無法捨棄直欄。");
		RESON_MAPPING.put("42818", "運算子或函數的運算元不相容或無法比較。");
		RESON_MAPPING.put("42819", "需要數字的算術運算運算元或函數運算元不是數字。");
		RESON_MAPPING.put("42820", "數字常數太長，或它的值不在其資料類型的範圍內。");
		RESON_MAPPING.put("42821", "更新或插入值與該欄不相容。");
		RESON_MAPPING.put("42823", "次查詢只容許一個直欄，但卻傳回多重直欄。");
		RESON_MAPPING.put("42824", "LIKE 的運算元不是字串，或第一個運算元不是直欄。");
		RESON_MAPPING.put("42825", "UNION、INTERSECT、EXCEPT 或 VALUES 的列沒有相容的直欄。");
		RESON_MAPPING.put("42826", "UNION、INTERSECT、EXCEPT 或 VALUES 的橫列數與直欄數不同。");
		RESON_MAPPING.put("42827", "UPDATE 或 DELETE 中識別的表格與游標指定的表格不同。");
		RESON_MAPPING.put("42828", "不能修改 UPDATE 或 DELETE 陳述式的游標所指定的表格，或者游標是唯讀的。");
		RESON_MAPPING.put("42829", "FOR UPDATE OF 無效，因為不能修改游標指定的結果表格。");
		RESON_MAPPING.put("42830", "外部索引鍵與母索引鍵的說明不相符。");
		RESON_MAPPING.put("42831", "主要索引鍵、唯一索引鍵、ROWID 或 ROW CHANGE TIMESTAMP 的直欄不容許空值。");
		RESON_MAPPING.put("42832", "系統物件上不允許此操作。");
		RESON_MAPPING.put("42834", "無法指定 SET NULL，因為無法指定空值給外部索引鍵的直欄。");
		RESON_MAPPING.put("42835", "指名的衍生表格間，不能指定循環參照。");
		RESON_MAPPING.put("42836", "遞迴的已指名衍生表格的規格無效。");
		RESON_MAPPING.put("42837", "無法變更直欄，因為它的屬性與目前直欄的屬性不相容。");
		RESON_MAPPING.put("42838", "偵測到無效的表格空間使用法。");
		RESON_MAPPING.put("42839", "索引和長直欄不能在與表格分離的表格空間內。");
		RESON_MAPPING.put("42840", "偵測到無效的 AS CAST 選項使用法。");
		RESON_MAPPING.put("42841", "參數記號不能是使用者定義的類型或參照類型。");
		RESON_MAPPING.put("42842", "直欄定義無效，因為指定的選項與直欄說明不一致。");
		RESON_MAPPING.put("42845", "偵測到無效的 VARIANT 或 EXTERNAL ACTION 函數的使用。");
		RESON_MAPPING.put("42846", "不支援從來源類型到目標類型的強制轉型。");
		RESON_MAPPING.put("42849", "外部常式不支援指定的選項。");
		RESON_MAPPING.put("42852", "GRANT 或 REVOKE 中指定的專用權無效或不一致。 （例如，視圖上的 GRANT ALTER。）");
		RESON_MAPPING.put("42853", "指定替代的選項，或是相同的選項指定了一次以上。");
		RESON_MAPPING.put("42854", "選取清單中的結果直欄資料類型無法與類型視圖或具體化查詢表格定義中所定義的類型相容。");
		RESON_MAPPING.put("42855", "不能將該 LOB 指定給這個主變數。 在提取此游標的所有 LOB 值時，所使用目標主變數必須是定位器或 LOB 變數。");
		RESON_MAPPING.put("42858", "作業不適用於指定的物件。");
		RESON_MAPPING.put("42863", "偵測到 REXX 中未定義的主變數。");
		RESON_MAPPING.put("42866", "CREATE FUNCTION 陳述式中，RETURNS 子句或 CAST FROM 子句中的資料類型，不適合原始函數或函數本體內 RETURN 陳述式中所傳回的資料類型。");
		RESON_MAPPING.put("42867", "指定衝突的選項。");
		RESON_MAPPING.put("42872", "FETCH 陳述式子句與游標定義不相容。");
		RESON_MAPPING.put("42875", "在 CREATE SCHEMA 內建立的物件必須具有與綱目名稱同樣的限定元。");
		RESON_MAPPING.put("42877", "無法定義直欄名稱。");
		RESON_MAPPING.put("42878", "以無效的函數或程序名稱與 EXTERNAL 關鍵字一起使用。");
		RESON_MAPPING.put("42879", "CREATE FUNCTION 陳述式中，一個或多個輸入參數的資料類型不適合原始函數中的對應資料類型。");
		RESON_MAPPING.put("42880", "CAST TO 和 CAST FROM 資料類型不相容，或是總是會造成固定字串截斷。");
		RESON_MAPPING.put("42881", "橫列函數使用無效。");
		RESON_MAPPING.put("42882", "特定實例名稱限定元不等於函數名稱限定元。");
		RESON_MAPPING.put("42883", "找不到具有相符標記的常式。");
		RESON_MAPPING.put("42884", "找不到具有指定名稱和相容引數的常式。");
		RESON_MAPPING.put("42885", "CREATE FUNCTION 陳述式上指定的輸入參數數目與 SOURCE 子句中 指名函數提供的數目不符。");
		RESON_MAPPING.put("42886", "IN、OUT 或 INOUT 參數屬性不符。");
		RESON_MAPPING.put("42887", "此函數在其所處的環境中是無效的。");
		RESON_MAPPING.put("42888", "表格沒有主要索引鍵。");
		RESON_MAPPING.put("42889", "表格已有主要索引鍵。");
		RESON_MAPPING.put("42890", "參照子句中指定了直欄清單，但是所識別的原始表格並無具有指定直欄名稱的唯一限制。");
		RESON_MAPPING.put("42891", "重複的 UNIQUE 限制已存在。");
		RESON_MAPPING.put("42893", "無法捨棄、變更或傳送物件或限制，或是無法從物件撤消權限，因為其他物件與其相依。");
		RESON_MAPPING.put("42894", "DEFAULT 值無效。");
		RESON_MAPPING.put("42895", "如為靜態 SQL，不能使用輸入主變數， 因為它的資料類型與程序或使用者定義的函數的參數不相容。");
		RESON_MAPPING.put("428A0", "使用者定義的函數所依據的來源函數發生錯誤。");
		RESON_MAPPING.put("428A1", "無法存取主機檔案變數參照的檔案。");
		RESON_MAPPING.put("428A2", "表格不能指定給多節點的節點群組，因為它沒有分段鍵。");
		RESON_MAPPING.put("428A3", "對事件監視器指定了無效的路徑。");
		RESON_MAPPING.put("428A4", "對事件監視器選項指定了無效的值。");
		RESON_MAPPING.put("428A5", "SET INTEGRITY 陳述式中所指名的異常狀況表格沒有適當的結構， 或是該表格已用產生的直欄、限制或觸發程式所定義。");
		RESON_MAPPING.put("428A6", "SET INTEGRITY 陳述式中所指名的異常狀況表格不能與任何檢查中的表格相同。");
		RESON_MAPPING.put("428A7", "檢查中的表格數與 SET INTEGRITY 陳述式所指定的異常狀況表格表格數不符。");
		RESON_MAPPING.put("428A8", "當母表格或基礎表格處於「設定設定擱置」狀態時，無法用衍生表格上的 SET INTEGRITY 陳述式重設「設定完整性擱置」狀態。");
		RESON_MAPPING.put("428A9", "節點範圍無效。");
		RESON_MAPPING.put("428AA", "該直欄名稱對事件監視器表格是無效的直欄。");
		RESON_MAPPING.put("428B0", "在 ROLLUP、CUBE 或 GROUPING SETS 內有非法的巢狀結構。");
		RESON_MAPPING.put("428B1", "不是針對特定節點設計的表格空間儲存器規格的數目不正確。");
		RESON_MAPPING.put("428B2", "儲存器的路徑名稱無效。");
		RESON_MAPPING.put("428B3", "指定無效的 SQLSTATE。");
		RESON_MAPPING.put("428B7", "SQL 陳述式中指定的數字超出有效範圍。");
		RESON_MAPPING.put("428BO", "無法為聯合資料來源建立計劃。");
		RESON_MAPPING.put("428C0", "無法捨棄節點，因為它是節點群組中唯一的節點。");
		RESON_MAPPING.put("428C1", "只能對表格指定一次直欄的資料類型或屬性。");
		RESON_MAPPING.put("428C2", "函數本體檢查指出在 CREATE FUNCTION 陳述式中應當已指定所提供的子句。");
		RESON_MAPPING.put("428C4", "述詞運算子每一邊的元素數目不相同。");
		RESON_MAPPING.put("428C5", "從資料來源中，找不到可用於資料類型的資料類型對映。");
		RESON_MAPPING.put("428C9", "不能將 ROWID 直欄指定為 INSERT 或 UPDATE 的目標直欄。");
		RESON_MAPPING.put("428CA", "添加模式中的表格不能有叢集索引。");
		RESON_MAPPING.put("428CB", "表格空間的分頁大小必須與相關的緩衝池分頁大小相符。");
		RESON_MAPPING.put("428D1", "無法存取 DATALINK 值所參照的檔案。");
		RESON_MAPPING.put("428D4", "FOR 陳述式所指定的游標無法在 OPEN、CLOSE 或 FETCH 陳述式中參照。");
		RESON_MAPPING.put("428D5", "結束標籤與開頭標籤不符。");
		RESON_MAPPING.put("428D6", "NOT ATOMIC 陳述式不容許使用 UNDO。");
		RESON_MAPPING.put("428D7", "不容許此條件值。");
		RESON_MAPPING.put("428D8", "宣告或使用 SQLSTATE 或 SQLCODE 變數無效。");
		RESON_MAPPING.put("428DB", "這是無法當作超類型、超表格、或超視圖的物件。");
		RESON_MAPPING.put("428DC", "對這個類型的轉換，此函數或方法無效。");
		RESON_MAPPING.put("428DD", "未定義必要的轉換。");
		RESON_MAPPING.put("428DE", "不支援 PAGESIZE 值。");
		RESON_MAPPING.put("428DF", "CREATE CAST 中指定的資料類型無效。");
		RESON_MAPPING.put("428DG", "CREATE CAST 中指定的函數無效。");
		RESON_MAPPING.put("428DH", "對類型表格而言，此作業無效。");
		RESON_MAPPING.put("428DJ", "不能變更或捨去繼承的直欄或屬性。");
		RESON_MAPPING.put("428DK", "已定義參照直欄的範圍。");
		RESON_MAPPING.put("428DL", "外部參數或原始函數的參數已定義一個範圍。");
		RESON_MAPPING.put("428DM", "對此參照類型而言，範圍表格或視圖無效。");
		RESON_MAPPING.put("428DN", "SCOPE 未在外部函數的 RETURNS 子句中指定，或已在來源函數的 RETURNS 子句中指定。");
		RESON_MAPPING.put("428DP", "此類型不是一個結構化類型。");
		RESON_MAPPING.put("428DQ", "子表格或子視圖的綱目名稱，必須與它的超表格或超視圖相同。");
		RESON_MAPPING.put("428DR", "作業無法套用於子表格或子視圖。");
		RESON_MAPPING.put("428DS", "不能在子表格上定義指定直欄之索引。");
		RESON_MAPPING.put("428DT", "表示式運算元為無效的範圍參照類型。");
		RESON_MAPPING.put("428DU", "必需類型階層結構中不包括類型。");
		RESON_MAPPING.put("428DV", "反向參照運算子的左運算元無效。");
		RESON_MAPPING.put("428DW", "不能使用反向參照運算子參照物件 ID 直欄。");
		RESON_MAPPING.put("428DX", "定義類型表格或類型視圖階層結構的根表格或根視圖需要物件 ID 直欄。");
		RESON_MAPPING.put("428DY", "無法更新目標物件 tpe 的統計值。");
		RESON_MAPPING.put("428DZ", "不能更新物件 ID 直欄。");
		RESON_MAPPING.put("428E0", "索引定義與索引範圍定義不符。");
		RESON_MAPPING.put("428E1", "範圍產生之表格函數的結果與索引範圍之索引鍵變換表格函數的結果不一致。");
		RESON_MAPPING.put("428E2", "索引鍵目標參數之數目或類型與索引範圍之索引鍵轉換函數的數目或類型不符。");
		RESON_MAPPING.put("428E3", "索引範圍中函數的引數無效。");
		RESON_MAPPING.put("428E4", "CREATE INDEX EXTENSION 陳述式中不支援函數。");
		RESON_MAPPING.put("428E5", "SELECTIVITY 子句只能以使用者定義述詞指定。");
		RESON_MAPPING.put("428E6", "使用者定義述詞中方法的搜尋引數與索引範圍的相對搜尋方法中的不符合。");
		RESON_MAPPING.put("428E7", "使用者定義述詞中之比較運算子後面的運算元類型與 RETURNS 資料類型不相符。");
		RESON_MAPPING.put("428E8", "搜尋目標或搜尋引數參數與正在建立的函數參數名稱不符合。");
		RESON_MAPPING.put("428E9", "引數參數名稱不能在相同使用規則中同時被當作搜尋目標和搜尋引數。");
		RESON_MAPPING.put("428EA", "類型視圖中的全選是無效的。");
		RESON_MAPPING.put("428EB", "當可更新超視圖之相對直欄時，子視圖中的直欄不能是唯讀的。");
		RESON_MAPPING.put("428EC", "為具體化查詢表格指定的全選無效。");
		RESON_MAPPING.put("428ED", "無法建構 Datalink 或 Reference 類型屬性的結構化類型。");
		RESON_MAPPING.put("428EE", "對此資料來源而言，選項無效。");
		RESON_MAPPING.put("428EF", "對此資料來源而言，選項的值無效。");
		RESON_MAPPING.put("428EG", "對此資料來源而言，缺少必要的選項。");
		RESON_MAPPING.put("428EH", "無法 ADD 已定義的選項。");
		RESON_MAPPING.put("428EJ", "無法 SET 或 DROP 尚未新增的選項。");
		RESON_MAPPING.put("428EK", "宣告廣域暫存表格名稱的限定元必須是 SESSION。");
		RESON_MAPPING.put("428EL", "轉換函數無法與函數或方法搭配使用。");
		RESON_MAPPING.put("428EM", "需要 TRANSFORM GROUP 子句。");
		RESON_MAPPING.put("428EN", "指定了一個未使用的轉換群組。");
		RESON_MAPPING.put("428EP", "結構化類型無法直接或間接與其自身相依。");
		RESON_MAPPING.put("428EQ", "常式的傳回類型與主旨類型不同。");
		RESON_MAPPING.put("428ER", "捨棄方法主體之前，無法捨棄方法規格。");
		RESON_MAPPING.put("428ES", "方法主體未對應方法規格的語言類型。");
		RESON_MAPPING.put("428EU", "伺服器定義中未指定 TYPE 或 VERSION。");
		RESON_MAPPING.put("428EV", "這種類型的資料來源不支援透通機能。");
		RESON_MAPPING.put("428EW", "無法將此表格轉換為具體化查詢表格或從具體化查詢表格轉換此表格。");
		RESON_MAPPING.put("428EX", "常式無法作為轉換函數使用，因為該常式為內建函數或方法。");
		RESON_MAPPING.put("428EY", "使用者定義述詞中之搜尋目標的資料類型與 指定索引擴充之來源鍵的資料類型不符。");
		RESON_MAPPING.put("428EZ", "OLAP 函數的視窗規格無效。");
		RESON_MAPPING.put("428F0", "ROW 函數必須包括至少兩個直欄。");
		RESON_MAPPING.put("428F1", "SQL TABLE 函數必須傳回表格結果。");
		RESON_MAPPING.put("428F2", "在 SQL 程序中，RETURN 陳述式值的資料類型必須是 INTEGER。");
		RESON_MAPPING.put("428F3", "SCROLL 與 WITH RETURN 互斥。");
		RESON_MAPPING.put("428F4", "不允許游標在 FETCH 上指定的 SENSITIVITY。");
		RESON_MAPPING.put("428F6", "游標可捲動的，但結果表格包含表格函數的輸出。");
		RESON_MAPPING.put("428F7", "只適用於 SQL 常式的作業試圖在外部常式上執行。");
		RESON_MAPPING.put("428F9", "無法在環境定義中指定順序表示式。");
		RESON_MAPPING.put("428FA", "十進位數的小數位數必須是零。");
		RESON_MAPPING.put("428FB", "sequence-name 不能是由系統為 identity 直欄產生的順序。");
		RESON_MAPPING.put("428FC", "加密密碼的長度無效。");
		RESON_MAPPING.put("428FD", "用來解密的密碼與用來加密資料的密碼不相符。");
		RESON_MAPPING.put("428FE", "資料不是 ENCRYPT 函數的結果。");
		RESON_MAPPING.put("428FF", "緩衝池規格無效。");
		RESON_MAPPING.put("428FG", "暫置表格或具體化查詢表格定義無效。");
		RESON_MAPPING.put("428FH", "SET INTEGRITY 選項無效。");
		RESON_MAPPING.put("428FI", "已指定 ORDER OF，但表格指定元不包含 ORDER BY 子句。");
		RESON_MAPPING.put("428FJ", "視圖或具體化查詢表格的外部全選不允許 ORDER BY。");
		RESON_MAPPING.put("428FL", "不容許 SQL 資料變更陳述式位在指定它的環境定義中。");
		RESON_MAPPING.put("428FM", "SELECT 內的 INSERT 陳述式已指定一個不是對稱視圖的視圖。");
		RESON_MAPPING.put("428FP", "主旨視圖上的每一個作業種類，只容許一個 INSTEAD OF 觸發程式。");
		RESON_MAPPING.put("428FQ", "INSTEAD OF 不得指定如下的視圖：使用 WITH CHECK OPTION 定義的視圖、定義在另一個使用 WITH CHECK OPTION 定義的視圖的視圖， 或在利用 WITH ROW MOVEMENT 子句定義的視圖中形成巢狀的視圖。");
		RESON_MAPPING.put("428FT", "表格與指定的資料分割作業不相容。");
		RESON_MAPPING.put("428FU", "從 FROM SQL 轉換函數或方法傳回的內建類型， 不符合 TO SQL 轉換函數或方法的相對應內建類型。");
		RESON_MAPPING.put("428FV", "無法將方法定義為置換方法。");
		RESON_MAPPING.put("428FZ", "只有部分作業有定義 INSTEAD OF 觸發程式的視圖不能用做 MERGE 陳述式中的目標。");
		RESON_MAPPING.put("428G1", "資料分割區數超出表格的表格空間數。");
		RESON_MAPPING.put("428G2", "無法從表格捨棄最後一個資料分割區。");
		RESON_MAPPING.put("428G3", "當全選中的 SQL 資料變更陳述式的目標視圖具有已定義的 INSTEAD OF 觸發程式時，FINAL TABLE 將無效。");
		RESON_MAPPING.put("428G4", "無法使用 INPUT SEQUENCE 排序。");
		RESON_MAPPING.put("428G5", "UPDATE 陳述式的指定子句必須至少指定一個不是 INCLUDE 直欄的直欄。");
		RESON_MAPPING.put("428G6", "指定了在全選的 FROM 子句，無法從資料變更陳述式的目標選取的直欄。");
		RESON_MAPPING.put("428G7", "在已實施的參照限制中，不能參照暱稱。");
		RESON_MAPPING.put("428G8", "無法啟用視圖以進行查詢最佳化。");
		RESON_MAPPING.put("428GA", "無法新增、捨棄或變更聯合選項。");
		RESON_MAPPING.put("428GC", "指定的功能字串無效。");
		RESON_MAPPING.put("428GD", "PARTITION BY 子句必須指定單一直欄，且必須與 ORGANIZE BY 子句的第一個直欄相同。");
		RESON_MAPPING.put("428GE", "來源表格無法附加至分割的目標表格。");
		RESON_MAPPING.put("428GF", "授與角色是無效的，因為它會建立循環。");
		RESON_MAPPING.put("428GG", "使用容錯巢狀表格表示式無效。");
		RESON_MAPPING.put("428GI", "由於 XML 綱目文件遺漏，因此 XML 綱目不完整。");
		RESON_MAPPING.put("428GL", "已在另一個信任環境定義中指定信任環境定義所指定的系統授權 ID。");
		RESON_MAPPING.put("428GM", "信任環境定義已經定義為供此授權 ID 或 PUBLIC 使用。");
		RESON_MAPPING.put("428GN", "未在指定的信任環境定義中定義指定的授權 ID 或 PUBLIC。");
		RESON_MAPPING.put("428GO", "直欄選項在透通的 DDL 陳述式中無效。");
		RESON_MAPPING.put("428GP", "無法指定類型 ARRAY 之元件的多重元素。");
		RESON_MAPPING.put("428GQ", "授與的安全標籤與另一個已授與的安全標籤相衝突。");
		RESON_MAPPING.put("428GR", "具有相同存取類型（READ 或 WRITE）的安全標籤已授與授權 ID。");
		RESON_MAPPING.put("428GS", "為程序指定的選項值不符合相對應的來源程序選項。");
		RESON_MAPPING.put("428GT", "未使用安全原則來保護此表格。");
		RESON_MAPPING.put("428GU", "表格必須至少包括一個未隱含地隱藏的直欄。");
		RESON_MAPPING.put("428GV", "URI 是空字串。");
		RESON_MAPPING.put("428GZ", "SELECT 子句中所有指定的排序索引鍵實例皆不相同。");
		RESON_MAPPING.put("428H0", "編製子索引作業無法套用至類型不是 ARRAY 的物件。");
		RESON_MAPPING.put("428H1", "編製子索引表示式的資料類型不是小數位數為零的確切數字類型。");
		RESON_MAPPING.put("428H2", "不支援在環境定義中使用陣列類型。");
		RESON_MAPPING.put("428H3", "所指定的樹狀結構元素無效。");
		RESON_MAPPING.put("428H4", "在環境定義之外使用階層式查詢建構。");
		RESON_MAPPING.put("428H5", "外部結合運算子的使用無效。");
		RESON_MAPPING.put("42901", "直欄函數未包括直欄名稱。");
		RESON_MAPPING.put("42903", "無法使用聚集函數或 OLAP 函數。");
		RESON_MAPPING.put("42904", "由於編譯錯誤，未建立 SQL 程序。");
		RESON_MAPPING.put("42907", "字串太長。");
		RESON_MAPPING.put("42908", "陳述式未包括必要的直欄清單。");
		RESON_MAPPING.put("42910", "複合陳述式中不容許此陳述式。");
		RESON_MAPPING.put("42911", "十進位除法運算無效，因為其結果會有負比例。");
		RESON_MAPPING.put("42912", "不是游標選取陳述式 UPDATE 子句中可識別的直欄，所以不能更新直欄。");
		RESON_MAPPING.put("42914", "DELETE 無效，因為次查詢中參照的表格可能受此操作影響。");
		RESON_MAPPING.put("42915", "偵測到無效的參照限制。");
		RESON_MAPPING.put("42916", "不能建立別名，因為它會導致別名的重複鏈接。");
		RESON_MAPPING.put("42917", "無法明確地捨棄或變更物件。");
		RESON_MAPPING.put("42918", "不能使用系統定義的資料類型名稱（例如 INTEGER）建立使用者定義的資料類型。");
		RESON_MAPPING.put("42919", "不容許使用巢狀複合陳述式。");
		RESON_MAPPING.put("42921", "不能新增儲存器至表格空間。");
		RESON_MAPPING.put("42925", "遞迴的指名起源表格不能指定 SELECT DISTINCT，並且必須指定 UNION ALL。");
		RESON_MAPPING.put("42928", "無法將 WITH EMPTY TABLE 指定給表格。");
		RESON_MAPPING.put("42932", "程式準備假設不正確。");
		RESON_MAPPING.put("42939", "無法使用名稱，因為指定的 ID 保留給系統使用。");
		RESON_MAPPING.put("42961", "指定的伺服器名稱不符合現行伺服器。");
		RESON_MAPPING.put("42962", "長直欄、LOB 直欄、XML 直欄或結構化類型直欄不能用在索引、索引鍵或限制中。");
		RESON_MAPPING.put("42963", "安全標籤直欄的規格無效。");
		RESON_MAPPING.put("42968", "連線失敗，因為沒有現行軟體授權。");
		RESON_MAPPING.put("42969", "未建立資料包。");
		RESON_MAPPING.put("42972", "MERGE 陳述式的結合條件或 ON 子句中的一個表示式參照到多個運算元表格中的直欄。");
		RESON_MAPPING.put("42985", "常式中不容許使用此陳述式。");
		RESON_MAPPING.put("42987", "程序或觸發程式中不容許此陳述式。");
		RESON_MAPPING.put("42989", "使用表示式所產生、或作為橫列變更時間戳記，或是安全標籤直欄的直欄無法用於 BEFORE 觸發程式中。");
		RESON_MAPPING.put("42990", "因為索引鍵直欄不是分割鍵直欄的超集，所以不容許唯一索引或唯一限制。");
		RESON_MAPPING.put("42991", "目前僅在內部支援 BOOLEAN、BINARY 及 VARBINARY 資料類型。");
		RESON_MAPPING.put("42993", "定義的直欄太大而無法記載。");
		RESON_MAPPING.put("42994", "不支援原始裝置儲存器。");
		RESON_MAPPING.put("42995", "所要求的函數沒有用在廣域暫存表格。");
		RESON_MAPPING.put("42997", "本版的 DB2 應用要求程式、DB2 應用程式伺服器或兩者的綜合都不支援此功能。");
		RESON_MAPPING.put("429A1", "節點群組對表格空間而言無效。");
		RESON_MAPPING.put("429A9", "DataJoiner 無法處理 SQL 陳述式。");
		RESON_MAPPING.put("429B2", "結構化類型或直欄所指定的列入長度值太小。");
		RESON_MAPPING.put("429B3", "子表格不能定義物件。");
		RESON_MAPPING.put("429B4", "資料過濾函數不能為 LANGUAGE SQL 函數。");
		RESON_MAPPING.put("429B5", "索引範圍之實例參數的資料類型為無效。");
		RESON_MAPPING.put("429B8", "以 PARAMETER STYLE JAVA 定義的常式無法使用結構化類型作為參數或傳回類型。");
		RESON_MAPPING.put("429B9", "無法在屬性指定中使用 DEFAULT 或 NULL。");
		RESON_MAPPING.put("429BA", "FEDERATED 關鍵字必須與有關的聯合資料庫物件一起使用。");
		RESON_MAPPING.put("429BB", "在 SQL 常式中，不支援為參數或變數所指定的資料類型。");
		RESON_MAPPING.put("429BC", "ALTER TABLESPACE 陳述式中有多重儲存器動作。");
		RESON_MAPPING.put("429BE", "主要索引鍵或唯一鍵是維度子句中直欄的子集。");
		RESON_MAPPING.put("429BG", "範圍叢集化表格不支援這個函數。");
		RESON_MAPPING.put("429BH", "分割表格定義包含不受支援的直欄定義，其可能是身分直欄、資料鏈結直欄或 XML 直欄。");
		RESON_MAPPING.put("429BJ", "無法在視圖中使用 WITH ROW MOVEMENT。");
		RESON_MAPPING.put("429BK", "嘗試更新視圖無效，因為移動橫列時，包括基礎視圖。");
		RESON_MAPPING.put("429BL", "在不合法的環境定義中呼叫了一個會修改 SQL 資料的函數。");
		RESON_MAPPING.put("429BM", "無法在這個環境定義中使用對照。");
		RESON_MAPPING.put("429BO", "無法為聯合資料來源建立計劃。");
		RESON_MAPPING.put("429BP", "無效的暱稱直欄表示式。");
		RESON_MAPPING.put("429BS", "XMLPATTERN 子句或以 XML 資料類型定義的直欄具有無效的索引定義。");
		RESON_MAPPING.put("429BT", "由於相依關係，傳送所有權失敗。");
		RESON_MAPPING.put("429BU", "無法存取用於外掛程式之使用者對映儲存庫的使用者對映。");
		RESON_MAPPING.put("429BV", "ROW CHANGE TIMESTAMP 直欄規格無效。");
		RESON_MAPPING.put("429BZ", "因為其中一份基礎表格受到保護，所以更新、刪除或插入 UNION ALL 視圖的作業失敗。");
		RESON_MAPPING.put("429C0", "查詢必須包含一個使用指出之直欄的述詞。");
		RESON_MAPPING.put("429C2", "在指定資料類型的環境定義中，為陣列指定的資料類型無效。");
		RESON_MAPPING.put("44000", "由於結果橫列不符合視圖定義，所以不容許插入或更新作業。");
		RESON_MAPPING.put("46001", "Java DDL - 無效 URL。");
		RESON_MAPPING.put("46002", "Java DDL - 無效 jar 名稱。");
		RESON_MAPPING.put("46003", "Java DDL - 無效類別刪除。");
		RESON_MAPPING.put("46007", "Java DDL - 無效標記。");
		RESON_MAPPING.put("46008", "Java DDL - 無效的方法指定。");
		RESON_MAPPING.put("46103", "Java 常式發現 ClassNotFound 異常狀況。");
		RESON_MAPPING.put("46501", "Java DDL - 未實作選用的元件。");
		RESON_MAPPING.put("51002", "找不到對應 SQL 陳述式執行要求的資料包。");
		RESON_MAPPING.put("51003", "一致性記號不相符。");
		RESON_MAPPING.put("51004", "SQLDA 內的位址無效。");
		RESON_MAPPING.put("51005", "先前的系統錯誤已停用這個函數。");
		RESON_MAPPING.put("51008", "前置編譯程式的版本號碼無效。");
		RESON_MAPPING.put("51015", "嘗試執行一個在連結時發現有錯誤的區段。");
		RESON_MAPPING.put("51017", "使用者沒有登入。");
		RESON_MAPPING.put("51018", "應用程式因錯誤而處於未連接狀態。");
		RESON_MAPPING.put("51021", "要等到應用程式處理執行 Roll back 操作後，才能執行 SQL 陳述式。");
		RESON_MAPPING.put("51022", "與 CONNECT 陳述式中指名伺服器的連線（現行的或休止的）已存在時，指定授權名稱的 CONNECT 無效。");
		RESON_MAPPING.put("51023", "資料庫已由資料庫管理程式的另一實例使用中。");
		RESON_MAPPING.put("51024", "不能使用檢視視圖，因為它已標記為不作用。");
		RESON_MAPPING.put("51025", "在 XA 交易處理環境中的應用程式，與 SYNCPOINT TWOPHASE 無關。");
		RESON_MAPPING.put("51026", "無法啟用事件監視器，因為它的目標路徑已由另一事件監視器使用中。");
		RESON_MAPPING.put("51027", "SET INTEGRITY 陳述式的 IMMEDIATE CHECKED 選項無效，因為表格是使用者所維護的具體化查詢表格或不在「設定完整性擱置」狀態中。");
		RESON_MAPPING.put("51028", "無法使用資料包，因為它已標記為不作用。");
		RESON_MAPPING.put("51030", "在應用程式處理中，尚未呼叫 ALLOCATE CURSOR 或 ASSOCIATE LOCATORS 陳述式所參照的程序。");
		RESON_MAPPING.put("51034", "已定義 MODIFIES SQL DATA 的常式在呼叫它的環境定義中是無效的。");
		RESON_MAPPING.put("51035", "無法使用 PREVIOUS VALUES 表示式，因為目前為止在階段作業中還未產生順序值。");
		RESON_MAPPING.put("51038", "常式可能無法再發出 SQL 陳述式。");
		RESON_MAPPING.put("51039", "未設定 ENCRYPTION PASSWORD 值。");
		RESON_MAPPING.put("51040", "編譯環境無效。");
		RESON_MAPPING.put("51041", "在 XA 交易內無法發出 SQL 陳述式。");
		RESON_MAPPING.put("51042", "無法收集統計值，因為沒有作用中的統計值事件監視器。");
		RESON_MAPPING.put("53038", "索引鍵限制值數為零，或大於索引鍵中的直欄數。");
		RESON_MAPPING.put("53040", "無法依指定來變更緩衝池。");
		RESON_MAPPING.put("53045", "索引鍵限制常數的資料類型與直欄的資料類型不同。");
		RESON_MAPPING.put("53090", "只有同一個編碼方法的資料（ASCII、EBCDIC 或 Unicode 其中一個），才可在相同的 SQL 陳述式中被參考。");
		RESON_MAPPING.put("53091", "指定的編碼方法，與目前用於所包含物件的編碼方法不同。");
		RESON_MAPPING.put("54001", "陳述式太長或者太複雜。");
		RESON_MAPPING.put("54002", "字串常數太長。");
		RESON_MAPPING.put("54004", "陳述式的 SELECT 或 INSERT 清單中，有太多表格名稱或太多項目。");
		RESON_MAPPING.put("54006", "連接的結果太長。");
		RESON_MAPPING.put("54008", "索引鍵太長、索引鍵的直欄太長，或索引鍵有太多直欄。");
		RESON_MAPPING.put("54010", "表格的記錄長度太長。");
		RESON_MAPPING.put("54011", "指定太多欄給表格或視圖。");
		RESON_MAPPING.put("54023", "函數或程序的參數或引數數目已超過限制。");
		RESON_MAPPING.put("54028", "已達並行 LOB 名稱的最大數目。");
		RESON_MAPPING.put("54029", "已達開啟目錄掃描的最大數目。");
		RESON_MAPPING.put("54030", "作用中的事件監視器已達最大數目。");
		RESON_MAPPING.put("54031", "指定該事件監視器的檔案已達最大數目。");
		RESON_MAPPING.put("54032", "已達表格的大小上限。");
		RESON_MAPPING.put("54033", "已達分割對映表的最大數。");
		RESON_MAPPING.put("54034", "表格空間所有儲存器名稱的組合長度太長。");
		RESON_MAPPING.put("54035", "內部物件限制已超出。");
		RESON_MAPPING.put("54036", "儲存器或儲存體路徑的路徑名稱太長。");
		RESON_MAPPING.put("54037", "該表格空間的儲存器對映過於複雜。");
		RESON_MAPPING.put("54038", "超過巢狀常式或觸發程式的最大深度。");
		RESON_MAPPING.put("54040", "轉移變數和轉移標籤直欄的參照太多，或這些參照的列長度太長。");
		RESON_MAPPING.put("54045", "已超出類型階層結構的最大層次。");
		RESON_MAPPING.put("54046", "索引範圍中可容許參數的最大值已超出。");
		RESON_MAPPING.put("54047", "已超出表格空間的大小上限。");
		RESON_MAPPING.put("54048", "沒有足夠分頁大小的暫存表格空間。");
		RESON_MAPPING.put("54049", "結構化類型的實例長度超出系統限制。");
		RESON_MAPPING.put("54050", "已超過結構化類型中所允許的屬性最大值。");
		RESON_MAPPING.put("54052", "緩衝池的區塊頁數對於緩衝池大小來說過大。");
		RESON_MAPPING.put("54053", "為 BLOCKSIZE 指定的值不在有效範圍內。");
		RESON_MAPPING.put("54054", "超過分割區數，或超過表格空間分割區數與分割限制索引鍵相對應長度的組合。");
		RESON_MAPPING.put("54057", "XML 元素名稱、屬性名稱、名稱空間字首或 URI 太長。");
		RESON_MAPPING.put("54058", "XML 路徑的內部表示法太長。");
		RESON_MAPPING.put("54059", "僅具有空格字元的文字節點字串值，對於 STRIP WHITESPACE 處理來說太長。");
		RESON_MAPPING.put("54061", "為安全標籤元件指定過多元素。");
		RESON_MAPPING.put("54062", "已超出安全原則中元件的最大數。");
		RESON_MAPPING.put("54063", "已達到事件監視器的 PCTDEACTIVATE 限制。");
		RESON_MAPPING.put("54064", "已開啟 65533 個以上的游標實例。");
		RESON_MAPPING.put("54066", "遞迴限制已超出階層式查詢範圍。");
		RESON_MAPPING.put("54067", "已超出連線數目上限。");
		RESON_MAPPING.put("55001", "資料庫必須移轉。");
		RESON_MAPPING.put("55002", "未正確定義解譯表格。");
		RESON_MAPPING.put("55006", "無法捨棄物件，因為目前在使用中。");
		RESON_MAPPING.put("55007", "不能改變物件，因為它目前由同一應用程式處理使用中。");
		RESON_MAPPING.put("55009", "系統嘗試寫入唯讀檔案或寫入保護磁片。");
		RESON_MAPPING.put("55012", "叢集索引已存在於表格上。");
		RESON_MAPPING.put("55019", "表格處於作業的無效狀態中。");
		RESON_MAPPING.put("55022", "檔案伺服器不是用這個資料庫登錄。");
		RESON_MAPPING.put("55023", "呼叫常式時發生錯誤。");
		RESON_MAPPING.put("55024", "無法終止表格空間，因為與表格相關的資料也在另一表格空間裡。");
		RESON_MAPPING.put("55025", "必須重新起始資料庫。");
		RESON_MAPPING.put("55026", "不能終止暫存表格空間。");
		RESON_MAPPING.put("55031", "錯誤對映檔的格式不正確。");
		RESON_MAPPING.put("55032", "CONNECT 陳述式無效，因為應用程式起始後，資料庫管理程式已停止。");
		RESON_MAPPING.put("55033", "不能在建立或修改事件監視器的同一工作單元內啟動事件監視器。");
		RESON_MAPPING.put("55034", "事件監視器處於無效的作業狀態。");
		RESON_MAPPING.put("55035", "無法捨棄表格，因為它是受保護的。");
		RESON_MAPPING.put("55037", "不能捨棄分割鍵，因為表格在多節點的節點群組中。");
		RESON_MAPPING.put("55038", "不能使用節點群組，因為正在將它重新平衡中。");
		RESON_MAPPING.put("55039", "不容許存取或狀態轉移，因為表格空間不在適當的狀態中。");
		RESON_MAPPING.put("55040", "資料庫的分割映像檔是處於暫停狀態。");
		RESON_MAPPING.put("55041", "重新平衡進行中時，不能將儲存器新增至表格空間。");
		RESON_MAPPING.put("55043", "當以一個結構化類型為基礎的類型表格或類型視圖存在時，無法變更此結構化類型的屬性。");
		RESON_MAPPING.put("55045", "無法建立此常式的 SQL 保存 (SAR) 檔案，因為一個必要的元件無法在伺服器中使用。");
		RESON_MAPPING.put("55046", "指定的 SQL 保存不符合目標環境。");
		RESON_MAPPING.put("55047", "外部函數或方法試圖存取聯合物件。");
		RESON_MAPPING.put("55048", "無法加密已加密的資料。");
		RESON_MAPPING.put("55049", "未適當地定義事件監視器表格。");
		RESON_MAPPING.put("55051", "ALTER BUFFERPOOL 陳述式目前正在處理中。");
		RESON_MAPPING.put("55054", "無法將方法定義為置換方法。");
		RESON_MAPPING.put("55056", "無法更新暱稱統計資料，原因是資料庫未啟用聯合功能。");
		RESON_MAPPING.put("55057", "不容許陳述式，因為它會使某些相依表格的漸進式維護失效。");
		RESON_MAPPING.put("55060", "尚未定義資料庫的自動儲存體。");
		RESON_MAPPING.put("55061", "無法針對自動儲存體表格空間變更表格空間儲存體。");
		RESON_MAPPING.put("55062", "無法提供儲存體路徑，因為未對資料庫啟用自動儲存體。");
		RESON_MAPPING.put("55063", "XML 綱目未處於作業的正確狀態中。");
		RESON_MAPPING.put("55064", "由於表格沒有安全原則，所以無法將基於標籤的存取控制套用至直欄。");
		RESON_MAPPING.put("55065", "一個表格最多可以有一個安全原則。");
		RESON_MAPPING.put("55066", "因為索引尚不支援大型 RID，所以表格無法配置新頁面。");
		RESON_MAPPING.put("55067", "因為 MQT 或暫置表格相依於表格，所以無法讓它成為受保護的表格。");
		RESON_MAPPING.put("55068", "無法使用橫列變更時間戳記表示式，因為表格沒有橫列變更時間戳記���");
		RESON_MAPPING.put("55069", "不支援使用定義為隔離的封套，建立或呼叫所獲得的程序。");
		RESON_MAPPING.put("55070", "未適當地定義管理作業表格。");
		RESON_MAPPING.put("56016", "為資料分割區指定了無效範圍。");
		RESON_MAPPING.put("56031", "子句或純量函數無效，因為此系統上不支援混合的與 DBCS 資料。");
		RESON_MAPPING.put("56033", "長字串直欄的插入或更新值，必須是主變數或 NULL。");
		RESON_MAPPING.put("56038", "此環境不支援所要求的功能。");
		RESON_MAPPING.put("56072", "由於舊版伺服器不支援函數，造成執行失敗，但不影響後續 SQL 陳述式的執行。");
		RESON_MAPPING.put("56084", "在選取清單或輸入清單中發現不受支援的 SQLTYPE。");
		RESON_MAPPING.put("56091", "由於執行組合 SQL 陳述式，發生多重錯誤。");
		RESON_MAPPING.put("56092", "無法決定授權類型，因為授權名稱並未專門識別使用者 ID、群組 ID 或角色。");
		RESON_MAPPING.put("56095", "連結選項無效。");
		RESON_MAPPING.put("56097", "在 DEVICE 上建立的 TABLESPACE 中，不允許 LONG VARCHAR 和 LONG VARGRAPHIC 欄位。");
		RESON_MAPPING.put("56098", "在隱含式的重新連結或準備期間，發生了一個錯誤。");
		RESON_MAPPING.put("56099", "目標資料庫不支援 REAL 資料類型。");
		RESON_MAPPING.put("560A0", "無法對 LOB 值執行動作。");
		RESON_MAPPING.put("560AA", "只有 Unicode 資料庫圖形資料才支援使用此子句或純量函數。");
		RESON_MAPPING.put("560AC", "外層定義無法用於所指定的資料來源類型或版本。");
		RESON_MAPPING.put("560AF", "當使用 gateway concentrator 時，不支援 PREPARE 陳述式。");
		RESON_MAPPING.put("560B0", "用來調整表格空間大小或表格空間儲存器大小的新大小值無效。");
		RESON_MAPPING.put("560B1", "在儲存程序中的游標規格無效。");
		RESON_MAPPING.put("560B7", "對多列 INSERT 來說，每一列的順序表示式用法必須相同。");
		RESON_MAPPING.put("560BB", "對於在動態準備的 CALL 陳述式中的 INOUT 參數，必須在 USING 與 INTO 子句中使用相同的主變數。");
		RESON_MAPPING.put("560BC", "存取檔案時發生錯誤。");
		RESON_MAPPING.put("560BD", "聯合伺服器收到來自資料來源的異常錯誤碼。");
		RESON_MAPPING.put("560BF", "加密機能無法使用。");
		RESON_MAPPING.put("560C0", "以 Unicode 編碼方法所建立的表格，無法在 SQL 函數或 SQL 方法中使用。");
		RESON_MAPPING.put("560C1", "以 Unicode 編碼方法所建立的表格，無法成為類型表格，也無法包含圖形類型或使用者定義類型。");
		RESON_MAPPING.put("560C2", "為捨棄的表格寫入一個歷程檔案項目失敗。");
		RESON_MAPPING.put("560C3", "AFTER 觸發程式無法修改要針對 INSERT 陳述式插入的橫列。");
		RESON_MAPPING.put("560C5", "必須重新連結資料包，才能順利執行。");
		RESON_MAPPING.put("560C6", "參照限制無法修改 SQL 資料變更陳述式已在全選內修改的橫列。");
		RESON_MAPPING.put("560C8", "無法更新部分的暱稱統計資料。");
		RESON_MAPPING.put("560C9", "無法解譯指定的陳述式。");
		RESON_MAPPING.put("560CB", "聯合伺服器從 Web 服務資料來源接收到 SOAP 錯誤。");
		RESON_MAPPING.put("560CD", "擷取警示配置設定時，所指定的一個以上值無效。");
		RESON_MAPPING.put("560CE", "由於最近的確定或 rollback 作業，導致參照無法使用 SQL 變數。");
		RESON_MAPPING.put("560CF", "表格空間無法轉換為 LARGE 表格空間。");
		RESON_MAPPING.put("560CG", "XML 值包含 XML 節點的組合，導致超出內部 ID 限制。");
		RESON_MAPPING.put("560CH", "已超出 XML 值中之 XML 節點的子節點上限。");
		RESON_MAPPING.put("560CI", "指定要傳回用戶端的結果集無效。");
		RESON_MAPPING.put("560CJ", "表格空間必須建立在 IBMCATGROUP 資料庫分割區群組中。");
		RESON_MAPPING.put("560CL", "這個資料來源中不支援建立或變更所獲得的程序。");
		RESON_MAPPING.put("560CN", "Wrapper 與安裝在聯合伺服器上的 DB2 版次不相容。");
		RESON_MAPPING.put("560CO", "階層式查詢中偵測到循環。");
		RESON_MAPPING.put("560CP", "多重橫列的插入或更新作業失敗，因為無法針對定義為 ROW CHANGE TIMESTAMP 及 GENERATED BY DEFAULT 的直欄同時指定 DEFAULT 及明確的值。");
		RESON_MAPPING.put("57001", "此表格無法使用，因為它沒有主要索引。");
		RESON_MAPPING.put("57003", "尚未啟動指定的緩衝池。");
		RESON_MAPPING.put("57007", "物件不能使用，因為 DROP 或 ALTER 擱置中。");
		RESON_MAPPING.put("57009", "暫時沒有可用的虛擬儲存體或資料庫資源。");
		RESON_MAPPING.put("57011", "沒有可用的虛擬儲存體或資料庫資源。");
		RESON_MAPPING.put("57012", "沒有可用的非資料庫資源。 這不會影響後續陳述式的成功執行。");
		RESON_MAPPING.put("57013", "沒有可用的非資料庫資源。 這將會影響後續陳述式的成功執行。");
		RESON_MAPPING.put("57014", "處理程序已依照要求取消。");
		RESON_MAPPING.put("57016", "因為表格不在作用中，所以不能存取它。");
		RESON_MAPPING.put("57017", "未定義字元轉換。");
		RESON_MAPPING.put("57019", "陳述式因為資源問題而未成功。");
		RESON_MAPPING.put("57020", "含有資料庫的磁碟機已被鎖定。");
		RESON_MAPPING.put("57021", "軟碟機的門沒關。");
		RESON_MAPPING.put("57022", "無法建立表格，因為陳述式的授權 ID 未擁有任何適當的資料庫空間 (dbspace)。");
		RESON_MAPPING.put("57030", "與應用程式伺服器的連線會超過安裝定義的限制。");
		RESON_MAPPING.put("57032", "已經起始並行資料庫的最大數目。");
		RESON_MAPPING.put("57033", "發生鎖死或逾時而無自動 Rollback。");
		RESON_MAPPING.put("57036", "交易日誌不屬於現行資料庫。");
		RESON_MAPPING.put("57046", "無法起始新的交易，因為資料庫或實例無活動。");
		RESON_MAPPING.put("57047", "無法建立內部資料庫檔案，因為不能存取目錄。");
		RESON_MAPPING.put("57048", "存取表格空間的儲存器時，發生錯誤。");
		RESON_MAPPING.put("57049", "已達作業系統程序限制。");
		RESON_MAPPING.put("57050", "檔案伺服器目前無法使用。");
		RESON_MAPPING.put("57051", "所估計的 CPU 用量超出資源限制。");
		RESON_MAPPING.put("57052", "無法使用節點，因為它沒有所有暫存表格空間的儲存器。");
		RESON_MAPPING.put("57053", "因為作業衝突，表格上無法執行該作業。");
		RESON_MAPPING.put("57055", "無法使用有足夠分頁大小的暫存表格空間。");
		RESON_MAPPING.put("57056", "無法使用資料包，因為資料庫在 NO PACKAGE LOCK 模式中。");
		RESON_MAPPING.put("57057", "因為之前 SQL 陳述式的 DRDA 鏈中所發生的情況，而導致無法執行 SQL 陳述式。");
		RESON_MAPPING.put("57059", "表格空間中的空間不足以執行指定的動作。");
		RESON_MAPPING.put("57060", "因為沒有可用的傳輸，所以無法處理陳述式。");
		RESON_MAPPING.put("58004", "系統發生錯誤（不一定會導致後續 SQL 陳述式無法成功執行）。");
		RESON_MAPPING.put("58005", "系統發生錯誤（導致後續 SQL 陳述式無法成功執行）。");
		RESON_MAPPING.put("58008", "由於分佈通訊協定錯誤致使執行失敗，它不影響後續 DDM 指令或 SQL 陳述式的成功執行。");
		RESON_MAPPING.put("58009", "由於分佈通訊協定錯誤致使執行失敗，造成交談解除配置。");
		RESON_MAPPING.put("58010", "由於分佈通訊協定錯誤致使執行失敗，它將影響後續 DDM 指令或 SQL 陳述式的成功執行。");
		RESON_MAPPING.put("58011", "連結程序進行時，DDM 指令無效。");
		RESON_MAPPING.put("58012", "具有指定資料包名稱與一致性記號的連結程序不在作用中。");
		RESON_MAPPING.put("58014", "不支援 DDM 指令。");
		RESON_MAPPING.put("58015", "不支援 DDM 物件。");
		RESON_MAPPING.put("58016", "不支援 DDM 參數。");
		RESON_MAPPING.put("58017", "不支援 DDM 參數值。");
		RESON_MAPPING.put("58018", "不支援 DDM 回答訊息。");
		RESON_MAPPING.put("58023", "系統錯誤已使得現行程式取消執行。");
		RESON_MAPPING.put("58030", "發生 I/O 錯誤。");
		RESON_MAPPING.put("58031", "由於系統錯誤，連線未成功。");
		RESON_MAPPING.put("58032", "無法將程序用於隔離模式的使用者定義的函數。");
		RESON_MAPPING.put("58034", "嘗試尋找頁面 DMS 表格空間裡的物件時，偵測到錯誤。");
		RESON_MAPPING.put("58035", "嘗試釋放頁面給 DMS 表格空間裡的物件時，偵測到錯誤。");
		RESON_MAPPING.put("58036", "指定的內部表格空間 ID 不存在。");
		RESON_MAPPING.put("58038", "由於叢集管理程式錯誤致使執行失敗，並不影響後續 SQL 陳述式的成功執行。");
		RESON_MAPPING.put("5U001", "不支援指定的功能或特性。");
		RESON_MAPPING.put("5U002", "指定的應用程式目前不存在。");
		RESON_MAPPING.put("5U003", "找不到活動監視器報告。");
		RESON_MAPPING.put("5U004", "儲存監視作業時，所提供的一個以上值無效。");
		RESON_MAPPING.put("5U005", "指定的動作模式無效。");
		RESON_MAPPING.put("5U006", "未開啟必要的監視器開關。");
		RESON_MAPPING.put("5U007", "傳回 CLP 錯誤。請參閱 CLP 訊息文件，以取得詳細資訊。");
		RESON_MAPPING.put("5U008", "公用程式作業 ID 無效。");
		RESON_MAPPING.put("5U009", "已達到儲存體路徑的最大數目。");
		RESON_MAPPING.put("5U010", "非型錄資料庫分割區上的還原作業無法指定自動儲存體路徑。");
		RESON_MAPPING.put("5U011", "還原作業必須指定自動儲存體路徑。");
		RESON_MAPPING.put("5U012", "路徑中資料庫分割區表示式的用法無效或不正確。");
		RESON_MAPPING.put("5U013", "無法繼續還原，因為資料庫分割區不可用。");
		RESON_MAPPING.put("5U014", "此授權 ID 沒有對表格執行 LOAD 指令的必要 LBAC 認證。");
		RESON_MAPPING.put("5U015", "在「使用方法 N 匯入」中，不支援 PC/IXF 檔案。");
		RESON_MAPPING.put("5U016", "此時無法取消所識別的活動。");
		RESON_MAPPING.put("5U017", "只能對資料庫或服務超類別定義一個工作動作集。");
		RESON_MAPPING.put("5U018", "對映工作動作中指定的服務次類別不能是預設服務次類別。");
		RESON_MAPPING.put("5U019", "FROM 與 TO 參數中指定的範圍無效。");
		RESON_MAPPING.put("5U020", "工作量無法服務要求，因為已停用或不允許其存取資料庫。");
		RESON_MAPPING.put("5U021", "直到應用程式處理執行確定或 Rollback 作業後，才能執行 SQL 陳述式。");
		RESON_MAPPING.put("5U022", "無法從工作量定義捨棄最後一個連線屬性。");
		RESON_MAPPING.put("5U023", "無法捨棄工作量，因為不是已停用它，就是它具有作用中的工作量事件。");
		RESON_MAPPING.put("5U024", "未啟動事件監視器，因為相同類型的事件監視器已在作用中。");
		RESON_MAPPING.put("5U025", "無法捨棄臨界值，因為未停用它、它具有不是空白的佇列，或活動正在臨界值控制下執行。");
		RESON_MAPPING.put("5U026", "已超出臨界值。已停止執行。");
		RESON_MAPPING.put("5U027", "已超出資料庫或服務超類別的服務類別數目上限。");
		RESON_MAPPING.put("5U028", "無法執行要求，因為已停用服務類別。");
		RESON_MAPPING.put("5U029", "無法在預設服務類別下建立服務子類別。");
		RESON_MAPPING.put("5U030", "與外部工作量管理程式通訊時發生錯誤。");
		RESON_MAPPING.put("5U031", "無法捨棄服務類別，因為它有子類別、相關的工作量、工作動作集、工作動作、連線、活動或臨界值，或未停用它，或它是預設服務類別。");
		RESON_MAPPING.put("5U032", "無法按指定方式來變更預設服務類別。");
		RESON_MAPPING.put("5U033", "PREVENT EXECUTION 工作動作已套用至活動，因此未執行活動。");
		RESON_MAPPING.put("5U034", "指定的工作動作類型對工作動作而言無效。");
		RESON_MAPPING.put("5U035", "活動不存在。");
		RESON_MAPPING.put("5U036", "Export 期間已截斷 PC/IXF 檔案中的直欄名稱。");
		RESON_MAPPING.put("5U037", "無法建立臨界值，因為它違反限制。");
		RESON_MAPPING.put("5U038", "未建立臨界值，因為具有相符定義的臨界值已存在。");
		RESON_MAPPING.put("5U039", "連線屬性的連線屬性值已存在，或偵測到重複的值。");
		RESON_MAPPING.put("5U040", "未對連線屬性定義指定的連線屬性值時，無法捨棄這個連線屬性值。");
		RESON_MAPPING.put("5U041", "指定的物件已使用審核原則。");
		RESON_MAPPING.put("5U042", "審核原則並未與指定的物件產生關聯。");
		RESON_MAPPING.put("5U043", "服務超類別不支援指定的子句。");
		RESON_MAPPING.put("5U0ZZ", "常式出現錯誤。請參閱 SQLCODE，以取得詳細資訊。");
		RESON_MAPPING.put("5UA01", "目前正在執行該作業，故無法將其移除。");

	}
	
	public boolean isDuplicate(int code){
		
		return DUPLICATE_CODE == code;
	}
	
	@Override
	public String getDescription(String statusCode){
		
		return RESON_MAPPING.get(statusCode);
	}
}
