
package com.systex.jbranch.fubon.commons.cbs.service_platform.jaxws_ri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceiverSoap", targetNamespace = "http://fubon.org/OperationImpl/ListenerServices/SOAP/Listener")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceiverSoap {


    /**
     * 
     * @param parameters
     */
    @WebMethod(operationName = "Operation", action = "/ListenerServices/SOAP/Listener")
    public void operation(
        @WebParam(name = "SoapService", targetNamespace = "http://fubon.com.tw/XSD/TCSSoapService", mode = WebParam.Mode.INOUT, partName = "parameters")
        Holder<SoapService> parameters);

}
