
package com.systex.jbranch.fubon.commons.cbs.service_platform.jaxws_ri;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TCSSOAPEMFListener", targetNamespace = "http://fubon.org/OperationImpl/ListenerServices/SOAP/Listener", wsdlLocation = "http://172.19.241.4:9214/ListenerServices/SOAP/Listener/TCSSOAPEMFListener?wsdl")
public class TCSSOAPEMFListener
    extends Service
{

    private final static URL TCSSOAPEMFLISTENER_WSDL_LOCATION;
    private final static WebServiceException TCSSOAPEMFLISTENER_EXCEPTION;
    private final static QName TCSSOAPEMFLISTENER_QNAME = new QName("http://fubon.org/OperationImpl/ListenerServices/SOAP/Listener", "TCSSOAPEMFListener");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.19.241.4:9214/ListenerServices/SOAP/Listener/TCSSOAPEMFListener?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TCSSOAPEMFLISTENER_WSDL_LOCATION = url;
        TCSSOAPEMFLISTENER_EXCEPTION = e;
    }

    public TCSSOAPEMFListener() {
        super(__getWsdlLocation(), TCSSOAPEMFLISTENER_QNAME);
    }

    public TCSSOAPEMFListener(WebServiceFeature... features) {
        super(__getWsdlLocation(), TCSSOAPEMFLISTENER_QNAME, features);
    }

    public TCSSOAPEMFListener(URL wsdlLocation) {
        super(wsdlLocation, TCSSOAPEMFLISTENER_QNAME);
    }

    public TCSSOAPEMFListener(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TCSSOAPEMFLISTENER_QNAME, features);
    }

    public TCSSOAPEMFListener(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TCSSOAPEMFListener(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReceiverSoap
     */
    @WebEndpoint(name = "SOAPListener")
    public ReceiverSoap getSOAPListener() {
        return super.getPort(new QName("http://fubon.org/OperationImpl/ListenerServices/SOAP/Listener", "SOAPListener"), ReceiverSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiverSoap
     */
    @WebEndpoint(name = "SOAPListener")
    public ReceiverSoap getSOAPListener(WebServiceFeature... features) {
        return super.getPort(new QName("http://fubon.org/OperationImpl/ListenerServices/SOAP/Listener", "SOAPListener"), ReceiverSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TCSSOAPEMFLISTENER_EXCEPTION!= null) {
            throw TCSSOAPEMFLISTENER_EXCEPTION;
        }
        return TCSSOAPEMFLISTENER_WSDL_LOCATION;
    }

}
