
package com.systex.jbranch.fubon.webservice.ws.FBMAPPService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetMappCaseSoap12", targetNamespace = "http://www.fubon.com/sso/webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetMappCaseSoap12 {


    /**
     * 
     * @param dataDisp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCase", action = "http://www.fubon.com/sso/webservices/GetCase")
    @WebResult(name = "GetCaseResult", targetNamespace = "http://www.fubon.com/sso/webservices/")
    @RequestWrapper(localName = "GetCase", targetNamespace = "http://www.fubon.com/sso/webservices/", className = "com.systex.jbranch.fubon.webservice.GetCase")
    @ResponseWrapper(localName = "GetCaseResponse", targetNamespace = "http://www.fubon.com/sso/webservices/", className = "com.systex.jbranch.fubon.webservice.GetCaseResponse")
    public String getCase(
        @WebParam(name = "DataDisp", targetNamespace = "http://www.fubon.com/sso/webservices/")
        String dataDisp);

}
