
package com.systex.jbranch.fubon.webservice.ws.FBMAPPService;

import javax.net.ssl.*;
import javax.xml.namespace.QName;
import javax.xml.ws.*;

import com.systex.jbranch.platform.common.dataManager.DataManager;

import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;


/**
 * 依照北富銀新理專系統所需，提供MAPP電子要保書欄位
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetMappCase", targetNamespace = "http://www.fubon.com/sso/webservices/", wsdlLocation = "src/webapp/resource/ws/FBMAPPService/GetMappCase.asmx.wsdl")
public class GetMappCase
    extends Service
{

    private final static URL GETMAPPCASE_WSDL_LOCATION;
    private static Exception GETMAPPCASE_EXCEPTION;
    private final static QName GETMAPPCASE_QNAME = new QName("http://www.fubon.com/sso/webservices/", "GetMappCase");

    static {
      URL url = null;

      try {


        TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
          public java.security.cert.X509Certificate[] getAcceptedIssuers() { return null; }
          public void checkClientTrusted(X509Certificate[] certs, String authType) { }
          public void checkServerTrusted(X509Certificate[] certs, String authType) { }

        } };

        SSLContext sc = SSLContext.getInstance("SSL");
        sc.init(null, trustAllCerts, new SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

        // Create all-trusting host name verifier
        HostnameVerifier allHostsValid = new HostnameVerifier() {
          public boolean verify(String hostname, SSLSession session) { return true; }
        };
        // Install the all-trusting host verifier
        HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid);


        WebServiceException e = null;
        url = GetMappCaseSoap.class.getResource("src/webapp/resource/ws/FBMAPPService/GetMappCase.asmx.wsdl");
        
      } catch (Exception e) {
        GETMAPPCASE_EXCEPTION = e;
      }
      GETMAPPCASE_WSDL_LOCATION = url;
    }

    public GetMappCase() throws Exception {
        super(__getWsdlLocation(), GETMAPPCASE_QNAME);
    }

    public GetMappCase(WebServiceFeature... features) throws Exception {
        super(__getWsdlLocation(), GETMAPPCASE_QNAME, features);
    }

    public GetMappCase(URL wsdlLocation) throws NoSuchAlgorithmException {
        super(wsdlLocation, GETMAPPCASE_QNAME);
    }

    public GetMappCase(URL wsdlLocation, WebServiceFeature... features) throws NoSuchAlgorithmException {
        super(wsdlLocation, GETMAPPCASE_QNAME, features);
    }

    public GetMappCase(URL wsdlLocation, QName serviceName) throws NoSuchAlgorithmException {
        super(wsdlLocation, serviceName);
    }

    public GetMappCase(URL wsdlLocation, QName serviceName, WebServiceFeature... features) throws NoSuchAlgorithmException {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetMappCaseSoap
     */
    @WebEndpoint(name = "GetMappCaseSoap")
    public GetMappCaseSoap getGetMappCaseSoap() {
        return super.getPort(new QName("http://www.fubon.com/sso/webservices/", "GetMappCaseSoap"), GetMappCaseSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMappCaseSoap
     */
    @WebEndpoint(name = "GetMappCaseSoap")
    public GetMappCaseSoap getGetMappCaseSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fubon.com/sso/webservices/", "GetMappCaseSoap"), GetMappCaseSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns GetMappCaseSoap
     */
    @WebEndpoint(name = "GetMappCaseSoap12")
    public GetMappCaseSoap12 getGetMappCaseSoap12() {
        return super.getPort(new QName("http://www.fubon.com/sso/webservices/", "GetMappCaseSoap12"), GetMappCaseSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetMappCaseSoap
     */
    @WebEndpoint(name = "GetMappCaseSoap12")
    public GetMappCaseSoap12 getGetMappCaseSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fubon.com/sso/webservices/", "GetMappCaseSoap12"), GetMappCaseSoap12.class, features);
    }

    private static URL __getWsdlLocation() throws Exception {
        if (GETMAPPCASE_EXCEPTION!= null) {
            throw GETMAPPCASE_EXCEPTION;
        }
        return GETMAPPCASE_WSDL_LOCATION;
    }

}
